// Code generated by ent, DO NOT EDIT.

package actionaudit

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the actionaudit type in the database.
	Label = "action_audit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDuplicateGroupID holds the string denoting the duplicate_group_id field in the database.
	FieldDuplicateGroupID = "duplicate_group_id"
	// FieldActor holds the string denoting the actor field in the database.
	FieldActor = "actor"
	// FieldActionType holds the string denoting the action_type field in the database.
	FieldActionType = "action_type"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldPerformedAt holds the string denoting the performed_at field in the database.
	FieldPerformedAt = "performed_at"
	// FieldStubbed holds the string denoting the stubbed field in the database.
	FieldStubbed = "stubbed"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeDuplicateGroup holds the string denoting the duplicate_group edge name in mutations.
	EdgeDuplicateGroup = "duplicate_group"
	// Table holds the table name of the actionaudit in the database.
	Table = "action_audits"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "action_audits"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// DuplicateGroupTable is the table that holds the duplicate_group relation/edge.
	DuplicateGroupTable = "action_audits"
	// DuplicateGroupInverseTable is the table name for the DuplicateGroup entity.
	// It exists in this package in order to avoid circular dependency with the "duplicategroup" package.
	DuplicateGroupInverseTable = "duplicate_groups"
	// DuplicateGroupColumn is the table column denoting the duplicate_group relation/edge.
	DuplicateGroupColumn = "duplicate_group_id"
)

// Columns holds all SQL columns for actionaudit fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTenantID,
	FieldDuplicateGroupID,
	FieldActor,
	FieldActionType,
	FieldPayload,
	FieldPerformedAt,
	FieldStubbed,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultActor holds the default value on creation for the "actor" field.
	DefaultActor string
	// DefaultPerformedAt holds the default value on creation for the "performed_at" field.
	DefaultPerformedAt func() time.Time
	// DefaultStubbed holds the default value on creation for the "stubbed" field.
	DefaultStubbed bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ActionType defines the type for the "action_type" enum field.
type ActionType string

// ActionType values.
const (
	ActionTypeAssignKeeper    ActionType = "assign_keeper"
	ActionTypeDeleteCopies    ActionType = "delete_copies"
	ActionTypeCreateHardlinks ActionType = "create_hardlinks"
	ActionTypeQuarantine      ActionType = "quarantine"
	ActionTypeRetry           ActionType = "retry"
	ActionTypeNote            ActionType = "note"
)

func (at ActionType) String() string {
	return string(at)
}

// ActionTypeValidator is a validator for the "action_type" field enum values. It is called by the builders before save.
func ActionTypeValidator(at ActionType) error {
	switch at {
	case ActionTypeAssignKeeper, ActionTypeDeleteCopies, ActionTypeCreateHardlinks, ActionTypeQuarantine, ActionTypeRetry, ActionTypeNote:
		return nil
	default:
		return fmt.Errorf("actionaudit: invalid enum value for action_type field: %q", at)
	}
}

// OrderOption defines the ordering options for the ActionAudit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDuplicateGroupID orders the results by the duplicate_group_id field.
func ByDuplicateGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuplicateGroupID, opts...).ToFunc()
}

// ByActor orders the results by the actor field.
func ByActor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActor, opts...).ToFunc()
}

// ByActionType orders the results by the action_type field.
func ByActionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionType, opts...).ToFunc()
}

// ByPerformedAt orders the results by the performed_at field.
func ByPerformedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerformedAt, opts...).ToFunc()
}

// ByStubbed orders the results by the stubbed field.
func ByStubbed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStubbed, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByDuplicateGroupField orders the results by duplicate_group field.
func ByDuplicateGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDuplicateGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newDuplicateGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DuplicateGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DuplicateGroupTable, DuplicateGroupColumn),
	)
}
