// Code generated by ent, DO NOT EDIT.

package actionaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldUpdateTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldTenantID, v))
}

// DuplicateGroupID applies equality check predicate on the "duplicate_group_id" field. It's identical to DuplicateGroupIDEQ.
func DuplicateGroupID(v uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldDuplicateGroupID, v))
}

// Actor applies equality check predicate on the "actor" field. It's identical to ActorEQ.
func Actor(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldActor, v))
}

// PerformedAt applies equality check predicate on the "performed_at" field. It's identical to PerformedAtEQ.
func PerformedAt(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldPerformedAt, v))
}

// Stubbed applies equality check predicate on the "stubbed" field. It's identical to StubbedEQ.
func Stubbed(v bool) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldStubbed, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLTE(FieldUpdateTime, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotIn(FieldTenantID, vs...))
}

// DuplicateGroupIDEQ applies the EQ predicate on the "duplicate_group_id" field.
func DuplicateGroupIDEQ(v uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldDuplicateGroupID, v))
}

// DuplicateGroupIDNEQ applies the NEQ predicate on the "duplicate_group_id" field.
func DuplicateGroupIDNEQ(v uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldDuplicateGroupID, v))
}

// DuplicateGroupIDIn applies the In predicate on the "duplicate_group_id" field.
func DuplicateGroupIDIn(vs ...uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIn(FieldDuplicateGroupID, vs...))
}

// DuplicateGroupIDNotIn applies the NotIn predicate on the "duplicate_group_id" field.
func DuplicateGroupIDNotIn(vs ...uuid.UUID) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotIn(FieldDuplicateGroupID, vs...))
}

// ActorEQ applies the EQ predicate on the "actor" field.
func ActorEQ(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldActor, v))
}

// ActorNEQ applies the NEQ predicate on the "actor" field.
func ActorNEQ(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldActor, v))
}

// ActorIn applies the In predicate on the "actor" field.
func ActorIn(vs ...string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIn(FieldActor, vs...))
}

// ActorNotIn applies the NotIn predicate on the "actor" field.
func ActorNotIn(vs ...string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotIn(FieldActor, vs...))
}

// ActorGT applies the GT predicate on the "actor" field.
func ActorGT(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGT(FieldActor, v))
}

// ActorGTE applies the GTE predicate on the "actor" field.
func ActorGTE(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGTE(FieldActor, v))
}

// ActorLT applies the LT predicate on the "actor" field.
func ActorLT(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLT(FieldActor, v))
}

// ActorLTE applies the LTE predicate on the "actor" field.
func ActorLTE(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLTE(FieldActor, v))
}

// ActorContains applies the Contains predicate on the "actor" field.
func ActorContains(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldContains(FieldActor, v))
}

// ActorHasPrefix applies the HasPrefix predicate on the "actor" field.
func ActorHasPrefix(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldHasPrefix(FieldActor, v))
}

// ActorHasSuffix applies the HasSuffix predicate on the "actor" field.
func ActorHasSuffix(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldHasSuffix(FieldActor, v))
}

// ActorEqualFold applies the EqualFold predicate on the "actor" field.
func ActorEqualFold(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEqualFold(FieldActor, v))
}

// ActorContainsFold applies the ContainsFold predicate on the "actor" field.
func ActorContainsFold(v string) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldContainsFold(FieldActor, v))
}

// ActionTypeEQ applies the EQ predicate on the "action_type" field.
func ActionTypeEQ(v ActionType) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldActionType, v))
}

// ActionTypeNEQ applies the NEQ predicate on the "action_type" field.
func ActionTypeNEQ(v ActionType) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldActionType, v))
}

// ActionTypeIn applies the In predicate on the "action_type" field.
func ActionTypeIn(vs ...ActionType) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIn(FieldActionType, vs...))
}

// ActionTypeNotIn applies the NotIn predicate on the "action_type" field.
func ActionTypeNotIn(vs ...ActionType) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotIn(FieldActionType, vs...))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotNull(FieldPayload))
}

// PerformedAtEQ applies the EQ predicate on the "performed_at" field.
func PerformedAtEQ(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldPerformedAt, v))
}

// PerformedAtNEQ applies the NEQ predicate on the "performed_at" field.
func PerformedAtNEQ(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldPerformedAt, v))
}

// PerformedAtIn applies the In predicate on the "performed_at" field.
func PerformedAtIn(vs ...time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldIn(FieldPerformedAt, vs...))
}

// PerformedAtNotIn applies the NotIn predicate on the "performed_at" field.
func PerformedAtNotIn(vs ...time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNotIn(FieldPerformedAt, vs...))
}

// PerformedAtGT applies the GT predicate on the "performed_at" field.
func PerformedAtGT(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGT(FieldPerformedAt, v))
}

// PerformedAtGTE applies the GTE predicate on the "performed_at" field.
func PerformedAtGTE(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldGTE(FieldPerformedAt, v))
}

// PerformedAtLT applies the LT predicate on the "performed_at" field.
func PerformedAtLT(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLT(FieldPerformedAt, v))
}

// PerformedAtLTE applies the LTE predicate on the "performed_at" field.
func PerformedAtLTE(v time.Time) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldLTE(FieldPerformedAt, v))
}

// StubbedEQ applies the EQ predicate on the "stubbed" field.
func StubbedEQ(v bool) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldEQ(FieldStubbed, v))
}

// StubbedNEQ applies the NEQ predicate on the "stubbed" field.
func StubbedNEQ(v bool) predicate.ActionAudit {
	return predicate.ActionAudit(sql.FieldNEQ(FieldStubbed, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.ActionAudit {
	return predicate.ActionAudit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.ActionAudit {
	return predicate.ActionAudit(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDuplicateGroup applies the HasEdge predicate on the "duplicate_group" edge.
func HasDuplicateGroup() predicate.ActionAudit {
	return predicate.ActionAudit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DuplicateGroupTable, DuplicateGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDuplicateGroupWith applies the HasEdge predicate on the "duplicate_group" edge with a given conditions (other predicates).
func HasDuplicateGroupWith(preds ...predicate.DuplicateGroup) predicate.ActionAudit {
	return predicate.ActionAudit(func(s *sql.Selector) {
		step := newDuplicateGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActionAudit) predicate.ActionAudit {
	return predicate.ActionAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActionAudit) predicate.ActionAudit {
	return predicate.ActionAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActionAudit) predicate.ActionAudit {
	return predicate.ActionAudit(sql.NotPredicates(p))
}
