// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ActionAudit is the predicate function for actionaudit builders.
type ActionAudit func(*sql.Selector)

// DuplicateGroup is the predicate function for duplicategroup builders.
type DuplicateGroup func(*sql.Selector)

// FileInstance is the predicate function for fileinstance builders.
type FileInstance func(*sql.Selector)

// Machine is the predicate function for machine builders.
type Machine func(*sql.Selector)

// Scan is the predicate function for scan builders.
type Scan func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)
