version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  disable:
    - exhaustruct

  settings:
    staticcheck:
      checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]

issues:
  max-same-issues: 3
  max-issues-per-linter: 50
