version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.22"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  disable:
    - exhaustruct

  settings:
    staticcheck:
      checks: ["*"]

issues:
  max-same-issues: 3
  max-issues-per-linter: 50
