run:
  timeout: 5m
  tests: true
  go: "1.22"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - unused
  disable:
    - exhaustruct

linters-settings:
  staticcheck:
    checks: ["*"]

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 50
