// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/actionaudit"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/predicate"
	"github.com/mcmx/duplynx/ent/tenant"
)

// ActionAuditQuery is the builder for querying ActionAudit entities.
type ActionAuditQuery struct {
	config
	ctx                *QueryContext
	order              []actionaudit.OrderOption
	inters             []Interceptor
	predicates         []predicate.ActionAudit
	withTenant         *TenantQuery
	withDuplicateGroup *DuplicateGroupQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ActionAuditQuery builder.
func (_q *ActionAuditQuery) Where(ps ...predicate.ActionAudit) *ActionAuditQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ActionAuditQuery) Limit(limit int) *ActionAuditQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ActionAuditQuery) Offset(offset int) *ActionAuditQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ActionAuditQuery) Unique(unique bool) *ActionAuditQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ActionAuditQuery) Order(o ...actionaudit.OrderOption) *ActionAuditQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *ActionAuditQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(actionaudit.Table, actionaudit.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, actionaudit.TenantTable, actionaudit.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDuplicateGroup chains the current query on the "duplicate_group" edge.
func (_q *ActionAuditQuery) QueryDuplicateGroup() *DuplicateGroupQuery {
	query := (&DuplicateGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(actionaudit.Table, actionaudit.FieldID, selector),
			sqlgraph.To(duplicategroup.Table, duplicategroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, actionaudit.DuplicateGroupTable, actionaudit.DuplicateGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ActionAudit entity from the query.
// Returns a *NotFoundError when no ActionAudit was found.
func (_q *ActionAuditQuery) First(ctx context.Context) (*ActionAudit, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{actionaudit.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ActionAuditQuery) FirstX(ctx context.Context) *ActionAudit {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ActionAudit ID from the query.
// Returns a *NotFoundError when no ActionAudit ID was found.
func (_q *ActionAuditQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{actionaudit.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ActionAuditQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ActionAudit entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ActionAudit entity is found.
// Returns a *NotFoundError when no ActionAudit entities are found.
func (_q *ActionAuditQuery) Only(ctx context.Context) (*ActionAudit, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{actionaudit.Label}
	default:
		return nil, &NotSingularError{actionaudit.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ActionAuditQuery) OnlyX(ctx context.Context) *ActionAudit {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ActionAudit ID in the query.
// Returns a *NotSingularError when more than one ActionAudit ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ActionAuditQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{actionaudit.Label}
	default:
		err = &NotSingularError{actionaudit.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ActionAuditQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ActionAudits.
func (_q *ActionAuditQuery) All(ctx context.Context) ([]*ActionAudit, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ActionAudit, *ActionAuditQuery]()
	return withInterceptors[[]*ActionAudit](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ActionAuditQuery) AllX(ctx context.Context) []*ActionAudit {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ActionAudit IDs.
func (_q *ActionAuditQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(actionaudit.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ActionAuditQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ActionAuditQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ActionAuditQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ActionAuditQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ActionAuditQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ActionAuditQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ActionAuditQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ActionAuditQuery) Clone() *ActionAuditQuery {
	if _q == nil {
		return nil
	}
	return &ActionAuditQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]actionaudit.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.ActionAudit{}, _q.predicates...),
		withTenant:         _q.withTenant.Clone(),
		withDuplicateGroup: _q.withDuplicateGroup.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ActionAuditQuery) WithTenant(opts ...func(*TenantQuery)) *ActionAuditQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithDuplicateGroup tells the query-builder to eager-load the nodes that are connected to
// the "duplicate_group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ActionAuditQuery) WithDuplicateGroup(opts ...func(*DuplicateGroupQuery)) *ActionAuditQuery {
	query := (&DuplicateGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDuplicateGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ActionAudit.Query().
//		GroupBy(actionaudit.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ActionAuditQuery) GroupBy(field string, fields ...string) *ActionAuditGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ActionAuditGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = actionaudit.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.ActionAudit.Query().
//		Select(actionaudit.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *ActionAuditQuery) Select(fields ...string) *ActionAuditSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ActionAuditSelect{ActionAuditQuery: _q}
	sbuild.label = actionaudit.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ActionAuditSelect configured with the given aggregations.
func (_q *ActionAuditQuery) Aggregate(fns ...AggregateFunc) *ActionAuditSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ActionAuditQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !actionaudit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ActionAuditQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ActionAudit, error) {
	var (
		nodes       = []*ActionAudit{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTenant != nil,
			_q.withDuplicateGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ActionAudit).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ActionAudit{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *ActionAudit, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDuplicateGroup; query != nil {
		if err := _q.loadDuplicateGroup(ctx, query, nodes, nil,
			func(n *ActionAudit, e *DuplicateGroup) { n.Edges.DuplicateGroup = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ActionAuditQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*ActionAudit, init func(*ActionAudit), assign func(*ActionAudit, *Tenant)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ActionAudit)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ActionAuditQuery) loadDuplicateGroup(ctx context.Context, query *DuplicateGroupQuery, nodes []*ActionAudit, init func(*ActionAudit), assign func(*ActionAudit, *DuplicateGroup)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ActionAudit)
	for i := range nodes {
		fk := nodes[i].DuplicateGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(duplicategroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "duplicate_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ActionAuditQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ActionAuditQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(actionaudit.Table, actionaudit.Columns, sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actionaudit.FieldID)
		for i := range fields {
			if fields[i] != actionaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(actionaudit.FieldTenantID)
		}
		if _q.withDuplicateGroup != nil {
			_spec.Node.AddColumnOnce(actionaudit.FieldDuplicateGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ActionAuditQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(actionaudit.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = actionaudit.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ActionAuditGroupBy is the group-by builder for ActionAudit entities.
type ActionAuditGroupBy struct {
	selector
	build *ActionAuditQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ActionAuditGroupBy) Aggregate(fns ...AggregateFunc) *ActionAuditGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ActionAuditGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActionAuditQuery, *ActionAuditGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ActionAuditGroupBy) sqlScan(ctx context.Context, root *ActionAuditQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ActionAuditSelect is the builder for selecting fields of ActionAudit entities.
type ActionAuditSelect struct {
	*ActionAuditQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ActionAuditSelect) Aggregate(fns ...AggregateFunc) *ActionAuditSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ActionAuditSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ActionAuditQuery, *ActionAuditSelect](ctx, _s.ActionAuditQuery, _s, _s.inters, v)
}

func (_s *ActionAuditSelect) sqlScan(ctx context.Context, root *ActionAuditQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
