// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/actionaudit"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/predicate"
	"github.com/mcmx/duplynx/ent/tenant"
)

// ActionAuditUpdate is the builder for updating ActionAudit entities.
type ActionAuditUpdate struct {
	config
	hooks    []Hook
	mutation *ActionAuditMutation
}

// Where appends a list predicates to the ActionAuditUpdate builder.
func (_u *ActionAuditUpdate) Where(ps ...predicate.ActionAudit) *ActionAuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ActionAuditUpdate) SetUpdateTime(v time.Time) *ActionAuditUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ActionAuditUpdate) SetTenantID(v uuid.UUID) *ActionAuditUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ActionAuditUpdate) SetNillableTenantID(v *uuid.UUID) *ActionAuditUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetDuplicateGroupID sets the "duplicate_group_id" field.
func (_u *ActionAuditUpdate) SetDuplicateGroupID(v uuid.UUID) *ActionAuditUpdate {
	_u.mutation.SetDuplicateGroupID(v)
	return _u
}

// SetNillableDuplicateGroupID sets the "duplicate_group_id" field if the given value is not nil.
func (_u *ActionAuditUpdate) SetNillableDuplicateGroupID(v *uuid.UUID) *ActionAuditUpdate {
	if v != nil {
		_u.SetDuplicateGroupID(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *ActionAuditUpdate) SetActor(v string) *ActionAuditUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *ActionAuditUpdate) SetNillableActor(v *string) *ActionAuditUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *ActionAuditUpdate) SetActionType(v actionaudit.ActionType) *ActionAuditUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *ActionAuditUpdate) SetNillableActionType(v *actionaudit.ActionType) *ActionAuditUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *ActionAuditUpdate) SetPayload(v map[string]interface{}) *ActionAuditUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *ActionAuditUpdate) ClearPayload() *ActionAuditUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetPerformedAt sets the "performed_at" field.
func (_u *ActionAuditUpdate) SetPerformedAt(v time.Time) *ActionAuditUpdate {
	_u.mutation.SetPerformedAt(v)
	return _u
}

// SetNillablePerformedAt sets the "performed_at" field if the given value is not nil.
func (_u *ActionAuditUpdate) SetNillablePerformedAt(v *time.Time) *ActionAuditUpdate {
	if v != nil {
		_u.SetPerformedAt(*v)
	}
	return _u
}

// SetStubbed sets the "stubbed" field.
func (_u *ActionAuditUpdate) SetStubbed(v bool) *ActionAuditUpdate {
	_u.mutation.SetStubbed(v)
	return _u
}

// SetNillableStubbed sets the "stubbed" field if the given value is not nil.
func (_u *ActionAuditUpdate) SetNillableStubbed(v *bool) *ActionAuditUpdate {
	if v != nil {
		_u.SetStubbed(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *ActionAuditUpdate) SetTenant(v *Tenant) *ActionAuditUpdate {
	return _u.SetTenantID(v.ID)
}

// SetDuplicateGroup sets the "duplicate_group" edge to the DuplicateGroup entity.
func (_u *ActionAuditUpdate) SetDuplicateGroup(v *DuplicateGroup) *ActionAuditUpdate {
	return _u.SetDuplicateGroupID(v.ID)
}

// Mutation returns the ActionAuditMutation object of the builder.
func (_u *ActionAuditUpdate) Mutation() *ActionAuditMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *ActionAuditUpdate) ClearTenant() *ActionAuditUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearDuplicateGroup clears the "duplicate_group" edge to the DuplicateGroup entity.
func (_u *ActionAuditUpdate) ClearDuplicateGroup() *ActionAuditUpdate {
	_u.mutation.ClearDuplicateGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActionAuditUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActionAuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionAuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActionAuditUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := actionaudit.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActionAuditUpdate) check() error {
	if v, ok := _u.mutation.ActionType(); ok {
		if err := actionaudit.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "ActionAudit.action_type": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActionAudit.tenant"`)
	}
	if _u.mutation.DuplicateGroupCleared() && len(_u.mutation.DuplicateGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActionAudit.duplicate_group"`)
	}
	return nil
}

func (_u *ActionAuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(actionaudit.Table, actionaudit.Columns, sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(actionaudit.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(actionaudit.FieldActor, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(actionaudit.FieldActionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(actionaudit.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(actionaudit.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.PerformedAt(); ok {
		_spec.SetField(actionaudit.FieldPerformedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Stubbed(); ok {
		_spec.SetField(actionaudit.FieldStubbed, field.TypeBool, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionaudit.TenantTable,
			Columns: []string{actionaudit.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionaudit.TenantTable,
			Columns: []string{actionaudit.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DuplicateGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionaudit.DuplicateGroupTable,
			Columns: []string{actionaudit.DuplicateGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DuplicateGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionaudit.DuplicateGroupTable,
			Columns: []string{actionaudit.DuplicateGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actionaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActionAuditUpdateOne is the builder for updating a single ActionAudit entity.
type ActionAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ActionAuditMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ActionAuditUpdateOne) SetUpdateTime(v time.Time) *ActionAuditUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ActionAuditUpdateOne) SetTenantID(v uuid.UUID) *ActionAuditUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ActionAuditUpdateOne) SetNillableTenantID(v *uuid.UUID) *ActionAuditUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetDuplicateGroupID sets the "duplicate_group_id" field.
func (_u *ActionAuditUpdateOne) SetDuplicateGroupID(v uuid.UUID) *ActionAuditUpdateOne {
	_u.mutation.SetDuplicateGroupID(v)
	return _u
}

// SetNillableDuplicateGroupID sets the "duplicate_group_id" field if the given value is not nil.
func (_u *ActionAuditUpdateOne) SetNillableDuplicateGroupID(v *uuid.UUID) *ActionAuditUpdateOne {
	if v != nil {
		_u.SetDuplicateGroupID(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *ActionAuditUpdateOne) SetActor(v string) *ActionAuditUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *ActionAuditUpdateOne) SetNillableActor(v *string) *ActionAuditUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *ActionAuditUpdateOne) SetActionType(v actionaudit.ActionType) *ActionAuditUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *ActionAuditUpdateOne) SetNillableActionType(v *actionaudit.ActionType) *ActionAuditUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *ActionAuditUpdateOne) SetPayload(v map[string]interface{}) *ActionAuditUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *ActionAuditUpdateOne) ClearPayload() *ActionAuditUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetPerformedAt sets the "performed_at" field.
func (_u *ActionAuditUpdateOne) SetPerformedAt(v time.Time) *ActionAuditUpdateOne {
	_u.mutation.SetPerformedAt(v)
	return _u
}

// SetNillablePerformedAt sets the "performed_at" field if the given value is not nil.
func (_u *ActionAuditUpdateOne) SetNillablePerformedAt(v *time.Time) *ActionAuditUpdateOne {
	if v != nil {
		_u.SetPerformedAt(*v)
	}
	return _u
}

// SetStubbed sets the "stubbed" field.
func (_u *ActionAuditUpdateOne) SetStubbed(v bool) *ActionAuditUpdateOne {
	_u.mutation.SetStubbed(v)
	return _u
}

// SetNillableStubbed sets the "stubbed" field if the given value is not nil.
func (_u *ActionAuditUpdateOne) SetNillableStubbed(v *bool) *ActionAuditUpdateOne {
	if v != nil {
		_u.SetStubbed(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *ActionAuditUpdateOne) SetTenant(v *Tenant) *ActionAuditUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetDuplicateGroup sets the "duplicate_group" edge to the DuplicateGroup entity.
func (_u *ActionAuditUpdateOne) SetDuplicateGroup(v *DuplicateGroup) *ActionAuditUpdateOne {
	return _u.SetDuplicateGroupID(v.ID)
}

// Mutation returns the ActionAuditMutation object of the builder.
func (_u *ActionAuditUpdateOne) Mutation() *ActionAuditMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *ActionAuditUpdateOne) ClearTenant() *ActionAuditUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearDuplicateGroup clears the "duplicate_group" edge to the DuplicateGroup entity.
func (_u *ActionAuditUpdateOne) ClearDuplicateGroup() *ActionAuditUpdateOne {
	_u.mutation.ClearDuplicateGroup()
	return _u
}

// Where appends a list predicates to the ActionAuditUpdate builder.
func (_u *ActionAuditUpdateOne) Where(ps ...predicate.ActionAudit) *ActionAuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActionAuditUpdateOne) Select(field string, fields ...string) *ActionAuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActionAudit entity.
func (_u *ActionAuditUpdateOne) Save(ctx context.Context) (*ActionAudit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionAuditUpdateOne) SaveX(ctx context.Context) *ActionAudit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActionAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionAuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ActionAuditUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := actionaudit.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActionAuditUpdateOne) check() error {
	if v, ok := _u.mutation.ActionType(); ok {
		if err := actionaudit.ActionTypeValidator(v); err != nil {
			return &ValidationError{Name: "action_type", err: fmt.Errorf(`ent: validator failed for field "ActionAudit.action_type": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActionAudit.tenant"`)
	}
	if _u.mutation.DuplicateGroupCleared() && len(_u.mutation.DuplicateGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActionAudit.duplicate_group"`)
	}
	return nil
}

func (_u *ActionAuditUpdateOne) sqlSave(ctx context.Context) (_node *ActionAudit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(actionaudit.Table, actionaudit.Columns, sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActionAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actionaudit.FieldID)
		for _, f := range fields {
			if !actionaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != actionaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(actionaudit.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(actionaudit.FieldActor, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(actionaudit.FieldActionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(actionaudit.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(actionaudit.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.PerformedAt(); ok {
		_spec.SetField(actionaudit.FieldPerformedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Stubbed(); ok {
		_spec.SetField(actionaudit.FieldStubbed, field.TypeBool, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionaudit.TenantTable,
			Columns: []string{actionaudit.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionaudit.TenantTable,
			Columns: []string{actionaudit.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DuplicateGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionaudit.DuplicateGroupTable,
			Columns: []string{actionaudit.DuplicateGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DuplicateGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionaudit.DuplicateGroupTable,
			Columns: []string{actionaudit.DuplicateGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ActionAudit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actionaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
