// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/actionaudit"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/tenant"
)

// ActionAudit is the model entity for the ActionAudit schema.
type ActionAudit struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// DuplicateGroupID holds the value of the "duplicate_group_id" field.
	DuplicateGroupID uuid.UUID `json:"duplicate_group_id,omitempty"`
	// Actor holds the value of the "actor" field.
	Actor string `json:"actor,omitempty"`
	// ActionType holds the value of the "action_type" field.
	ActionType actionaudit.ActionType `json:"action_type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// PerformedAt holds the value of the "performed_at" field.
	PerformedAt time.Time `json:"performed_at,omitempty"`
	// Stubbed holds the value of the "stubbed" field.
	Stubbed bool `json:"stubbed,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActionAuditQuery when eager-loading is set.
	Edges        ActionAuditEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActionAuditEdges holds the relations/edges for other nodes in the graph.
type ActionAuditEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// DuplicateGroup holds the value of the duplicate_group edge.
	DuplicateGroup *DuplicateGroup `json:"duplicate_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActionAuditEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// DuplicateGroupOrErr returns the DuplicateGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActionAuditEdges) DuplicateGroupOrErr() (*DuplicateGroup, error) {
	if e.DuplicateGroup != nil {
		return e.DuplicateGroup, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: duplicategroup.Label}
	}
	return nil, &NotLoadedError{edge: "duplicate_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ActionAudit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case actionaudit.FieldPayload:
			values[i] = new([]byte)
		case actionaudit.FieldStubbed:
			values[i] = new(sql.NullBool)
		case actionaudit.FieldActor, actionaudit.FieldActionType:
			values[i] = new(sql.NullString)
		case actionaudit.FieldCreateTime, actionaudit.FieldUpdateTime, actionaudit.FieldPerformedAt:
			values[i] = new(sql.NullTime)
		case actionaudit.FieldID, actionaudit.FieldTenantID, actionaudit.FieldDuplicateGroupID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ActionAudit fields.
func (_m *ActionAudit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case actionaudit.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case actionaudit.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case actionaudit.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case actionaudit.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case actionaudit.FieldDuplicateGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_group_id", values[i])
			} else if value != nil {
				_m.DuplicateGroupID = *value
			}
		case actionaudit.FieldActor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor", values[i])
			} else if value.Valid {
				_m.Actor = value.String
			}
		case actionaudit.FieldActionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action_type", values[i])
			} else if value.Valid {
				_m.ActionType = actionaudit.ActionType(value.String)
			}
		case actionaudit.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case actionaudit.FieldPerformedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field performed_at", values[i])
			} else if value.Valid {
				_m.PerformedAt = value.Time
			}
		case actionaudit.FieldStubbed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stubbed", values[i])
			} else if value.Valid {
				_m.Stubbed = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ActionAudit.
// This includes values selected through modifiers, order, etc.
func (_m *ActionAudit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the ActionAudit entity.
func (_m *ActionAudit) QueryTenant() *TenantQuery {
	return NewActionAuditClient(_m.config).QueryTenant(_m)
}

// QueryDuplicateGroup queries the "duplicate_group" edge of the ActionAudit entity.
func (_m *ActionAudit) QueryDuplicateGroup() *DuplicateGroupQuery {
	return NewActionAuditClient(_m.config).QueryDuplicateGroup(_m)
}

// Update returns a builder for updating this ActionAudit.
// Note that you need to call ActionAudit.Unwrap() before calling this method if this ActionAudit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ActionAudit) Update() *ActionAuditUpdateOne {
	return NewActionAuditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ActionAudit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ActionAudit) Unwrap() *ActionAudit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ActionAudit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ActionAudit) String() string {
	var builder strings.Builder
	builder.WriteString("ActionAudit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("duplicate_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DuplicateGroupID))
	builder.WriteString(", ")
	builder.WriteString("actor=")
	builder.WriteString(_m.Actor)
	builder.WriteString(", ")
	builder.WriteString("action_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionType))
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("performed_at=")
	builder.WriteString(_m.PerformedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("stubbed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stubbed))
	builder.WriteByte(')')
	return builder.String()
}

// ActionAudits is a parsable slice of ActionAudit.
type ActionAudits []*ActionAudit
