// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mcmx/duplynx/ent/actionaudit"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/fileinstance"
	"github.com/mcmx/duplynx/ent/machine"
	"github.com/mcmx/duplynx/ent/scan"
	"github.com/mcmx/duplynx/ent/tenant"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ActionAudit is the client for interacting with the ActionAudit builders.
	ActionAudit *ActionAuditClient
	// DuplicateGroup is the client for interacting with the DuplicateGroup builders.
	DuplicateGroup *DuplicateGroupClient
	// FileInstance is the client for interacting with the FileInstance builders.
	FileInstance *FileInstanceClient
	// Machine is the client for interacting with the Machine builders.
	Machine *MachineClient
	// Scan is the client for interacting with the Scan builders.
	Scan *ScanClient
	// Tenant is the client for interacting with the Tenant builders.
	Tenant *TenantClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ActionAudit = NewActionAuditClient(c.config)
	c.DuplicateGroup = NewDuplicateGroupClient(c.config)
	c.FileInstance = NewFileInstanceClient(c.config)
	c.Machine = NewMachineClient(c.config)
	c.Scan = NewScanClient(c.config)
	c.Tenant = NewTenantClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		ActionAudit:    NewActionAuditClient(cfg),
		DuplicateGroup: NewDuplicateGroupClient(cfg),
		FileInstance:   NewFileInstanceClient(cfg),
		Machine:        NewMachineClient(cfg),
		Scan:           NewScanClient(cfg),
		Tenant:         NewTenantClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		ActionAudit:    NewActionAuditClient(cfg),
		DuplicateGroup: NewDuplicateGroupClient(cfg),
		FileInstance:   NewFileInstanceClient(cfg),
		Machine:        NewMachineClient(cfg),
		Scan:           NewScanClient(cfg),
		Tenant:         NewTenantClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ActionAudit.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.ActionAudit, c.DuplicateGroup, c.FileInstance, c.Machine, c.Scan, c.Tenant,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.ActionAudit, c.DuplicateGroup, c.FileInstance, c.Machine, c.Scan, c.Tenant,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ActionAuditMutation:
		return c.ActionAudit.mutate(ctx, m)
	case *DuplicateGroupMutation:
		return c.DuplicateGroup.mutate(ctx, m)
	case *FileInstanceMutation:
		return c.FileInstance.mutate(ctx, m)
	case *MachineMutation:
		return c.Machine.mutate(ctx, m)
	case *ScanMutation:
		return c.Scan.mutate(ctx, m)
	case *TenantMutation:
		return c.Tenant.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ActionAuditClient is a client for the ActionAudit schema.
type ActionAuditClient struct {
	config
}

// NewActionAuditClient returns a client for the ActionAudit from the given config.
func NewActionAuditClient(c config) *ActionAuditClient {
	return &ActionAuditClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `actionaudit.Hooks(f(g(h())))`.
func (c *ActionAuditClient) Use(hooks ...Hook) {
	c.hooks.ActionAudit = append(c.hooks.ActionAudit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `actionaudit.Intercept(f(g(h())))`.
func (c *ActionAuditClient) Intercept(interceptors ...Interceptor) {
	c.inters.ActionAudit = append(c.inters.ActionAudit, interceptors...)
}

// Create returns a builder for creating a ActionAudit entity.
func (c *ActionAuditClient) Create() *ActionAuditCreate {
	mutation := newActionAuditMutation(c.config, OpCreate)
	return &ActionAuditCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ActionAudit entities.
func (c *ActionAuditClient) CreateBulk(builders ...*ActionAuditCreate) *ActionAuditCreateBulk {
	return &ActionAuditCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ActionAuditClient) MapCreateBulk(slice any, setFunc func(*ActionAuditCreate, int)) *ActionAuditCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ActionAuditCreateBulk{err: fmt.Errorf("calling to ActionAuditClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ActionAuditCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ActionAuditCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ActionAudit.
func (c *ActionAuditClient) Update() *ActionAuditUpdate {
	mutation := newActionAuditMutation(c.config, OpUpdate)
	return &ActionAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ActionAuditClient) UpdateOne(_m *ActionAudit) *ActionAuditUpdateOne {
	mutation := newActionAuditMutation(c.config, OpUpdateOne, withActionAudit(_m))
	return &ActionAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ActionAuditClient) UpdateOneID(id uuid.UUID) *ActionAuditUpdateOne {
	mutation := newActionAuditMutation(c.config, OpUpdateOne, withActionAuditID(id))
	return &ActionAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ActionAudit.
func (c *ActionAuditClient) Delete() *ActionAuditDelete {
	mutation := newActionAuditMutation(c.config, OpDelete)
	return &ActionAuditDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ActionAuditClient) DeleteOne(_m *ActionAudit) *ActionAuditDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ActionAuditClient) DeleteOneID(id uuid.UUID) *ActionAuditDeleteOne {
	builder := c.Delete().Where(actionaudit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ActionAuditDeleteOne{builder}
}

// Query returns a query builder for ActionAudit.
func (c *ActionAuditClient) Query() *ActionAuditQuery {
	return &ActionAuditQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeActionAudit},
		inters: c.Interceptors(),
	}
}

// Get returns a ActionAudit entity by its id.
func (c *ActionAuditClient) Get(ctx context.Context, id uuid.UUID) (*ActionAudit, error) {
	return c.Query().Where(actionaudit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ActionAuditClient) GetX(ctx context.Context, id uuid.UUID) *ActionAudit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTenant queries the tenant edge of a ActionAudit.
func (c *ActionAuditClient) QueryTenant(_m *ActionAudit) *TenantQuery {
	query := (&TenantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(actionaudit.Table, actionaudit.FieldID, id),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, actionaudit.TenantTable, actionaudit.TenantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDuplicateGroup queries the duplicate_group edge of a ActionAudit.
func (c *ActionAuditClient) QueryDuplicateGroup(_m *ActionAudit) *DuplicateGroupQuery {
	query := (&DuplicateGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(actionaudit.Table, actionaudit.FieldID, id),
			sqlgraph.To(duplicategroup.Table, duplicategroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, actionaudit.DuplicateGroupTable, actionaudit.DuplicateGroupColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ActionAuditClient) Hooks() []Hook {
	return c.hooks.ActionAudit
}

// Interceptors returns the client interceptors.
func (c *ActionAuditClient) Interceptors() []Interceptor {
	return c.inters.ActionAudit
}

func (c *ActionAuditClient) mutate(ctx context.Context, m *ActionAuditMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ActionAuditCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ActionAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ActionAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ActionAuditDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ActionAudit mutation op: %q", m.Op())
	}
}

// DuplicateGroupClient is a client for the DuplicateGroup schema.
type DuplicateGroupClient struct {
	config
}

// NewDuplicateGroupClient returns a client for the DuplicateGroup from the given config.
func NewDuplicateGroupClient(c config) *DuplicateGroupClient {
	return &DuplicateGroupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `duplicategroup.Hooks(f(g(h())))`.
func (c *DuplicateGroupClient) Use(hooks ...Hook) {
	c.hooks.DuplicateGroup = append(c.hooks.DuplicateGroup, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `duplicategroup.Intercept(f(g(h())))`.
func (c *DuplicateGroupClient) Intercept(interceptors ...Interceptor) {
	c.inters.DuplicateGroup = append(c.inters.DuplicateGroup, interceptors...)
}

// Create returns a builder for creating a DuplicateGroup entity.
func (c *DuplicateGroupClient) Create() *DuplicateGroupCreate {
	mutation := newDuplicateGroupMutation(c.config, OpCreate)
	return &DuplicateGroupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DuplicateGroup entities.
func (c *DuplicateGroupClient) CreateBulk(builders ...*DuplicateGroupCreate) *DuplicateGroupCreateBulk {
	return &DuplicateGroupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DuplicateGroupClient) MapCreateBulk(slice any, setFunc func(*DuplicateGroupCreate, int)) *DuplicateGroupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DuplicateGroupCreateBulk{err: fmt.Errorf("calling to DuplicateGroupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DuplicateGroupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DuplicateGroupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DuplicateGroup.
func (c *DuplicateGroupClient) Update() *DuplicateGroupUpdate {
	mutation := newDuplicateGroupMutation(c.config, OpUpdate)
	return &DuplicateGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DuplicateGroupClient) UpdateOne(_m *DuplicateGroup) *DuplicateGroupUpdateOne {
	mutation := newDuplicateGroupMutation(c.config, OpUpdateOne, withDuplicateGroup(_m))
	return &DuplicateGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DuplicateGroupClient) UpdateOneID(id uuid.UUID) *DuplicateGroupUpdateOne {
	mutation := newDuplicateGroupMutation(c.config, OpUpdateOne, withDuplicateGroupID(id))
	return &DuplicateGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DuplicateGroup.
func (c *DuplicateGroupClient) Delete() *DuplicateGroupDelete {
	mutation := newDuplicateGroupMutation(c.config, OpDelete)
	return &DuplicateGroupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DuplicateGroupClient) DeleteOne(_m *DuplicateGroup) *DuplicateGroupDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DuplicateGroupClient) DeleteOneID(id uuid.UUID) *DuplicateGroupDeleteOne {
	builder := c.Delete().Where(duplicategroup.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DuplicateGroupDeleteOne{builder}
}

// Query returns a query builder for DuplicateGroup.
func (c *DuplicateGroupClient) Query() *DuplicateGroupQuery {
	return &DuplicateGroupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDuplicateGroup},
		inters: c.Interceptors(),
	}
}

// Get returns a DuplicateGroup entity by its id.
func (c *DuplicateGroupClient) Get(ctx context.Context, id uuid.UUID) (*DuplicateGroup, error) {
	return c.Query().Where(duplicategroup.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DuplicateGroupClient) GetX(ctx context.Context, id uuid.UUID) *DuplicateGroup {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTenant queries the tenant edge of a DuplicateGroup.
func (c *DuplicateGroupClient) QueryTenant(_m *DuplicateGroup) *TenantQuery {
	query := (&TenantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, id),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, duplicategroup.TenantTable, duplicategroup.TenantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryScan queries the scan edge of a DuplicateGroup.
func (c *DuplicateGroupClient) QueryScan(_m *DuplicateGroup) *ScanQuery {
	query := (&ScanClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, id),
			sqlgraph.To(scan.Table, scan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, duplicategroup.ScanTable, duplicategroup.ScanColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryKeeperMachine queries the keeper_machine edge of a DuplicateGroup.
func (c *DuplicateGroupClient) QueryKeeperMachine(_m *DuplicateGroup) *MachineQuery {
	query := (&MachineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, id),
			sqlgraph.To(machine.Table, machine.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, duplicategroup.KeeperMachineTable, duplicategroup.KeeperMachineColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFileInstances queries the file_instances edge of a DuplicateGroup.
func (c *DuplicateGroupClient) QueryFileInstances(_m *DuplicateGroup) *FileInstanceQuery {
	query := (&FileInstanceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, id),
			sqlgraph.To(fileinstance.Table, fileinstance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, duplicategroup.FileInstancesTable, duplicategroup.FileInstancesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryActionAudits queries the action_audits edge of a DuplicateGroup.
func (c *DuplicateGroupClient) QueryActionAudits(_m *DuplicateGroup) *ActionAuditQuery {
	query := (&ActionAuditClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, id),
			sqlgraph.To(actionaudit.Table, actionaudit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, duplicategroup.ActionAuditsTable, duplicategroup.ActionAuditsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DuplicateGroupClient) Hooks() []Hook {
	return c.hooks.DuplicateGroup
}

// Interceptors returns the client interceptors.
func (c *DuplicateGroupClient) Interceptors() []Interceptor {
	return c.inters.DuplicateGroup
}

func (c *DuplicateGroupClient) mutate(ctx context.Context, m *DuplicateGroupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DuplicateGroupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DuplicateGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DuplicateGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DuplicateGroupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DuplicateGroup mutation op: %q", m.Op())
	}
}

// FileInstanceClient is a client for the FileInstance schema.
type FileInstanceClient struct {
	config
}

// NewFileInstanceClient returns a client for the FileInstance from the given config.
func NewFileInstanceClient(c config) *FileInstanceClient {
	return &FileInstanceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fileinstance.Hooks(f(g(h())))`.
func (c *FileInstanceClient) Use(hooks ...Hook) {
	c.hooks.FileInstance = append(c.hooks.FileInstance, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `fileinstance.Intercept(f(g(h())))`.
func (c *FileInstanceClient) Intercept(interceptors ...Interceptor) {
	c.inters.FileInstance = append(c.inters.FileInstance, interceptors...)
}

// Create returns a builder for creating a FileInstance entity.
func (c *FileInstanceClient) Create() *FileInstanceCreate {
	mutation := newFileInstanceMutation(c.config, OpCreate)
	return &FileInstanceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FileInstance entities.
func (c *FileInstanceClient) CreateBulk(builders ...*FileInstanceCreate) *FileInstanceCreateBulk {
	return &FileInstanceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FileInstanceClient) MapCreateBulk(slice any, setFunc func(*FileInstanceCreate, int)) *FileInstanceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FileInstanceCreateBulk{err: fmt.Errorf("calling to FileInstanceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FileInstanceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FileInstanceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FileInstance.
func (c *FileInstanceClient) Update() *FileInstanceUpdate {
	mutation := newFileInstanceMutation(c.config, OpUpdate)
	return &FileInstanceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileInstanceClient) UpdateOne(_m *FileInstance) *FileInstanceUpdateOne {
	mutation := newFileInstanceMutation(c.config, OpUpdateOne, withFileInstance(_m))
	return &FileInstanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileInstanceClient) UpdateOneID(id uuid.UUID) *FileInstanceUpdateOne {
	mutation := newFileInstanceMutation(c.config, OpUpdateOne, withFileInstanceID(id))
	return &FileInstanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FileInstance.
func (c *FileInstanceClient) Delete() *FileInstanceDelete {
	mutation := newFileInstanceMutation(c.config, OpDelete)
	return &FileInstanceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FileInstanceClient) DeleteOne(_m *FileInstance) *FileInstanceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FileInstanceClient) DeleteOneID(id uuid.UUID) *FileInstanceDeleteOne {
	builder := c.Delete().Where(fileinstance.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileInstanceDeleteOne{builder}
}

// Query returns a query builder for FileInstance.
func (c *FileInstanceClient) Query() *FileInstanceQuery {
	return &FileInstanceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFileInstance},
		inters: c.Interceptors(),
	}
}

// Get returns a FileInstance entity by its id.
func (c *FileInstanceClient) Get(ctx context.Context, id uuid.UUID) (*FileInstance, error) {
	return c.Query().Where(fileinstance.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileInstanceClient) GetX(ctx context.Context, id uuid.UUID) *FileInstance {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDuplicateGroup queries the duplicate_group edge of a FileInstance.
func (c *FileInstanceClient) QueryDuplicateGroup(_m *FileInstance) *DuplicateGroupQuery {
	query := (&DuplicateGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(fileinstance.Table, fileinstance.FieldID, id),
			sqlgraph.To(duplicategroup.Table, duplicategroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fileinstance.DuplicateGroupTable, fileinstance.DuplicateGroupColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMachine queries the machine edge of a FileInstance.
func (c *FileInstanceClient) QueryMachine(_m *FileInstance) *MachineQuery {
	query := (&MachineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(fileinstance.Table, fileinstance.FieldID, id),
			sqlgraph.To(machine.Table, machine.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fileinstance.MachineTable, fileinstance.MachineColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FileInstanceClient) Hooks() []Hook {
	return c.hooks.FileInstance
}

// Interceptors returns the client interceptors.
func (c *FileInstanceClient) Interceptors() []Interceptor {
	return c.inters.FileInstance
}

func (c *FileInstanceClient) mutate(ctx context.Context, m *FileInstanceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FileInstanceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FileInstanceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FileInstanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FileInstanceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FileInstance mutation op: %q", m.Op())
	}
}

// MachineClient is a client for the Machine schema.
type MachineClient struct {
	config
}

// NewMachineClient returns a client for the Machine from the given config.
func NewMachineClient(c config) *MachineClient {
	return &MachineClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `machine.Hooks(f(g(h())))`.
func (c *MachineClient) Use(hooks ...Hook) {
	c.hooks.Machine = append(c.hooks.Machine, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `machine.Intercept(f(g(h())))`.
func (c *MachineClient) Intercept(interceptors ...Interceptor) {
	c.inters.Machine = append(c.inters.Machine, interceptors...)
}

// Create returns a builder for creating a Machine entity.
func (c *MachineClient) Create() *MachineCreate {
	mutation := newMachineMutation(c.config, OpCreate)
	return &MachineCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Machine entities.
func (c *MachineClient) CreateBulk(builders ...*MachineCreate) *MachineCreateBulk {
	return &MachineCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MachineClient) MapCreateBulk(slice any, setFunc func(*MachineCreate, int)) *MachineCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MachineCreateBulk{err: fmt.Errorf("calling to MachineClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MachineCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MachineCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Machine.
func (c *MachineClient) Update() *MachineUpdate {
	mutation := newMachineMutation(c.config, OpUpdate)
	return &MachineUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MachineClient) UpdateOne(_m *Machine) *MachineUpdateOne {
	mutation := newMachineMutation(c.config, OpUpdateOne, withMachine(_m))
	return &MachineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MachineClient) UpdateOneID(id uuid.UUID) *MachineUpdateOne {
	mutation := newMachineMutation(c.config, OpUpdateOne, withMachineID(id))
	return &MachineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Machine.
func (c *MachineClient) Delete() *MachineDelete {
	mutation := newMachineMutation(c.config, OpDelete)
	return &MachineDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MachineClient) DeleteOne(_m *Machine) *MachineDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MachineClient) DeleteOneID(id uuid.UUID) *MachineDeleteOne {
	builder := c.Delete().Where(machine.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MachineDeleteOne{builder}
}

// Query returns a query builder for Machine.
func (c *MachineClient) Query() *MachineQuery {
	return &MachineQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMachine},
		inters: c.Interceptors(),
	}
}

// Get returns a Machine entity by its id.
func (c *MachineClient) Get(ctx context.Context, id uuid.UUID) (*Machine, error) {
	return c.Query().Where(machine.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MachineClient) GetX(ctx context.Context, id uuid.UUID) *Machine {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTenant queries the tenant edge of a Machine.
func (c *MachineClient) QueryTenant(_m *Machine) *TenantQuery {
	query := (&TenantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(machine.Table, machine.FieldID, id),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, machine.TenantTable, machine.TenantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryKeeperGroups queries the keeper_groups edge of a Machine.
func (c *MachineClient) QueryKeeperGroups(_m *Machine) *DuplicateGroupQuery {
	query := (&DuplicateGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(machine.Table, machine.FieldID, id),
			sqlgraph.To(duplicategroup.Table, duplicategroup.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, machine.KeeperGroupsTable, machine.KeeperGroupsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFileInstances queries the file_instances edge of a Machine.
func (c *MachineClient) QueryFileInstances(_m *Machine) *FileInstanceQuery {
	query := (&FileInstanceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(machine.Table, machine.FieldID, id),
			sqlgraph.To(fileinstance.Table, fileinstance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, machine.FileInstancesTable, machine.FileInstancesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInitiatedScans queries the initiated_scans edge of a Machine.
func (c *MachineClient) QueryInitiatedScans(_m *Machine) *ScanQuery {
	query := (&ScanClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(machine.Table, machine.FieldID, id),
			sqlgraph.To(scan.Table, scan.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, machine.InitiatedScansTable, machine.InitiatedScansColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MachineClient) Hooks() []Hook {
	return c.hooks.Machine
}

// Interceptors returns the client interceptors.
func (c *MachineClient) Interceptors() []Interceptor {
	return c.inters.Machine
}

func (c *MachineClient) mutate(ctx context.Context, m *MachineMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MachineCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MachineUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MachineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MachineDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Machine mutation op: %q", m.Op())
	}
}

// ScanClient is a client for the Scan schema.
type ScanClient struct {
	config
}

// NewScanClient returns a client for the Scan from the given config.
func NewScanClient(c config) *ScanClient {
	return &ScanClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `scan.Hooks(f(g(h())))`.
func (c *ScanClient) Use(hooks ...Hook) {
	c.hooks.Scan = append(c.hooks.Scan, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `scan.Intercept(f(g(h())))`.
func (c *ScanClient) Intercept(interceptors ...Interceptor) {
	c.inters.Scan = append(c.inters.Scan, interceptors...)
}

// Create returns a builder for creating a Scan entity.
func (c *ScanClient) Create() *ScanCreate {
	mutation := newScanMutation(c.config, OpCreate)
	return &ScanCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Scan entities.
func (c *ScanClient) CreateBulk(builders ...*ScanCreate) *ScanCreateBulk {
	return &ScanCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ScanClient) MapCreateBulk(slice any, setFunc func(*ScanCreate, int)) *ScanCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ScanCreateBulk{err: fmt.Errorf("calling to ScanClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ScanCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ScanCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Scan.
func (c *ScanClient) Update() *ScanUpdate {
	mutation := newScanMutation(c.config, OpUpdate)
	return &ScanUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScanClient) UpdateOne(_m *Scan) *ScanUpdateOne {
	mutation := newScanMutation(c.config, OpUpdateOne, withScan(_m))
	return &ScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScanClient) UpdateOneID(id uuid.UUID) *ScanUpdateOne {
	mutation := newScanMutation(c.config, OpUpdateOne, withScanID(id))
	return &ScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Scan.
func (c *ScanClient) Delete() *ScanDelete {
	mutation := newScanMutation(c.config, OpDelete)
	return &ScanDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScanClient) DeleteOne(_m *Scan) *ScanDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScanClient) DeleteOneID(id uuid.UUID) *ScanDeleteOne {
	builder := c.Delete().Where(scan.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScanDeleteOne{builder}
}

// Query returns a query builder for Scan.
func (c *ScanClient) Query() *ScanQuery {
	return &ScanQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeScan},
		inters: c.Interceptors(),
	}
}

// Get returns a Scan entity by its id.
func (c *ScanClient) Get(ctx context.Context, id uuid.UUID) (*Scan, error) {
	return c.Query().Where(scan.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScanClient) GetX(ctx context.Context, id uuid.UUID) *Scan {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTenant queries the tenant edge of a Scan.
func (c *ScanClient) QueryTenant(_m *Scan) *TenantQuery {
	query := (&TenantClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(scan.Table, scan.FieldID, id),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scan.TenantTable, scan.TenantColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInitiatedMachine queries the initiated_machine edge of a Scan.
func (c *ScanClient) QueryInitiatedMachine(_m *Scan) *MachineQuery {
	query := (&MachineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(scan.Table, scan.FieldID, id),
			sqlgraph.To(machine.Table, machine.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scan.InitiatedMachineTable, scan.InitiatedMachineColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDuplicateGroups queries the duplicate_groups edge of a Scan.
func (c *ScanClient) QueryDuplicateGroups(_m *Scan) *DuplicateGroupQuery {
	query := (&DuplicateGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(scan.Table, scan.FieldID, id),
			sqlgraph.To(duplicategroup.Table, duplicategroup.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, scan.DuplicateGroupsTable, scan.DuplicateGroupsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ScanClient) Hooks() []Hook {
	return c.hooks.Scan
}

// Interceptors returns the client interceptors.
func (c *ScanClient) Interceptors() []Interceptor {
	return c.inters.Scan
}

func (c *ScanClient) mutate(ctx context.Context, m *ScanMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScanCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScanUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScanUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScanDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Scan mutation op: %q", m.Op())
	}
}

// TenantClient is a client for the Tenant schema.
type TenantClient struct {
	config
}

// NewTenantClient returns a client for the Tenant from the given config.
func NewTenantClient(c config) *TenantClient {
	return &TenantClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tenant.Hooks(f(g(h())))`.
func (c *TenantClient) Use(hooks ...Hook) {
	c.hooks.Tenant = append(c.hooks.Tenant, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tenant.Intercept(f(g(h())))`.
func (c *TenantClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tenant = append(c.inters.Tenant, interceptors...)
}

// Create returns a builder for creating a Tenant entity.
func (c *TenantClient) Create() *TenantCreate {
	mutation := newTenantMutation(c.config, OpCreate)
	return &TenantCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tenant entities.
func (c *TenantClient) CreateBulk(builders ...*TenantCreate) *TenantCreateBulk {
	return &TenantCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TenantClient) MapCreateBulk(slice any, setFunc func(*TenantCreate, int)) *TenantCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TenantCreateBulk{err: fmt.Errorf("calling to TenantClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TenantCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TenantCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tenant.
func (c *TenantClient) Update() *TenantUpdate {
	mutation := newTenantMutation(c.config, OpUpdate)
	return &TenantUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TenantClient) UpdateOne(_m *Tenant) *TenantUpdateOne {
	mutation := newTenantMutation(c.config, OpUpdateOne, withTenant(_m))
	return &TenantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TenantClient) UpdateOneID(id uuid.UUID) *TenantUpdateOne {
	mutation := newTenantMutation(c.config, OpUpdateOne, withTenantID(id))
	return &TenantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tenant.
func (c *TenantClient) Delete() *TenantDelete {
	mutation := newTenantMutation(c.config, OpDelete)
	return &TenantDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TenantClient) DeleteOne(_m *Tenant) *TenantDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TenantClient) DeleteOneID(id uuid.UUID) *TenantDeleteOne {
	builder := c.Delete().Where(tenant.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TenantDeleteOne{builder}
}

// Query returns a query builder for Tenant.
func (c *TenantClient) Query() *TenantQuery {
	return &TenantQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTenant},
		inters: c.Interceptors(),
	}
}

// Get returns a Tenant entity by its id.
func (c *TenantClient) Get(ctx context.Context, id uuid.UUID) (*Tenant, error) {
	return c.Query().Where(tenant.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TenantClient) GetX(ctx context.Context, id uuid.UUID) *Tenant {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMachines queries the machines edge of a Tenant.
func (c *TenantClient) QueryMachines(_m *Tenant) *MachineQuery {
	query := (&MachineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, id),
			sqlgraph.To(machine.Table, machine.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.MachinesTable, tenant.MachinesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryScans queries the scans edge of a Tenant.
func (c *TenantClient) QueryScans(_m *Tenant) *ScanQuery {
	query := (&ScanClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, id),
			sqlgraph.To(scan.Table, scan.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.ScansTable, tenant.ScansColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDuplicateGroups queries the duplicate_groups edge of a Tenant.
func (c *TenantClient) QueryDuplicateGroups(_m *Tenant) *DuplicateGroupQuery {
	query := (&DuplicateGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, id),
			sqlgraph.To(duplicategroup.Table, duplicategroup.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.DuplicateGroupsTable, tenant.DuplicateGroupsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryActionAudits queries the action_audits edge of a Tenant.
func (c *TenantClient) QueryActionAudits(_m *Tenant) *ActionAuditQuery {
	query := (&ActionAuditClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tenant.Table, tenant.FieldID, id),
			sqlgraph.To(actionaudit.Table, actionaudit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tenant.ActionAuditsTable, tenant.ActionAuditsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TenantClient) Hooks() []Hook {
	return c.hooks.Tenant
}

// Interceptors returns the client interceptors.
func (c *TenantClient) Interceptors() []Interceptor {
	return c.inters.Tenant
}

func (c *TenantClient) mutate(ctx context.Context, m *TenantMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TenantCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TenantUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TenantUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TenantDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tenant mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ActionAudit, DuplicateGroup, FileInstance, Machine, Scan, Tenant []ent.Hook
	}
	inters struct {
		ActionAudit, DuplicateGroup, FileInstance, Machine, Scan,
		Tenant []ent.Interceptor
	}
)
