// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/actionaudit"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/fileinstance"
	"github.com/mcmx/duplynx/ent/machine"
	"github.com/mcmx/duplynx/ent/predicate"
	"github.com/mcmx/duplynx/ent/scan"
	"github.com/mcmx/duplynx/ent/tenant"
)

// DuplicateGroupUpdate is the builder for updating DuplicateGroup entities.
type DuplicateGroupUpdate struct {
	config
	hooks    []Hook
	mutation *DuplicateGroupMutation
}

// Where appends a list predicates to the DuplicateGroupUpdate builder.
func (_u *DuplicateGroupUpdate) Where(ps ...predicate.DuplicateGroup) *DuplicateGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DuplicateGroupUpdate) SetUpdateTime(v time.Time) *DuplicateGroupUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *DuplicateGroupUpdate) SetTenantID(v uuid.UUID) *DuplicateGroupUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *DuplicateGroupUpdate) SetNillableTenantID(v *uuid.UUID) *DuplicateGroupUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetScanID sets the "scan_id" field.
func (_u *DuplicateGroupUpdate) SetScanID(v uuid.UUID) *DuplicateGroupUpdate {
	_u.mutation.SetScanID(v)
	return _u
}

// SetNillableScanID sets the "scan_id" field if the given value is not nil.
func (_u *DuplicateGroupUpdate) SetNillableScanID(v *uuid.UUID) *DuplicateGroupUpdate {
	if v != nil {
		_u.SetScanID(*v)
	}
	return _u
}

// SetKeeperMachineID sets the "keeper_machine_id" field.
func (_u *DuplicateGroupUpdate) SetKeeperMachineID(v uuid.UUID) *DuplicateGroupUpdate {
	_u.mutation.SetKeeperMachineID(v)
	return _u
}

// SetNillableKeeperMachineID sets the "keeper_machine_id" field if the given value is not nil.
func (_u *DuplicateGroupUpdate) SetNillableKeeperMachineID(v *uuid.UUID) *DuplicateGroupUpdate {
	if v != nil {
		_u.SetKeeperMachineID(*v)
	}
	return _u
}

// ClearKeeperMachineID clears the value of the "keeper_machine_id" field.
func (_u *DuplicateGroupUpdate) ClearKeeperMachineID() *DuplicateGroupUpdate {
	_u.mutation.ClearKeeperMachineID()
	return _u
}

// SetHash sets the "hash" field.
func (_u *DuplicateGroupUpdate) SetHash(v string) *DuplicateGroupUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *DuplicateGroupUpdate) SetNillableHash(v *string) *DuplicateGroupUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DuplicateGroupUpdate) SetStatus(v duplicategroup.Status) *DuplicateGroupUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DuplicateGroupUpdate) SetNillableStatus(v *duplicategroup.Status) *DuplicateGroupUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFileCount sets the "file_count" field.
func (_u *DuplicateGroupUpdate) SetFileCount(v int) *DuplicateGroupUpdate {
	_u.mutation.ResetFileCount()
	_u.mutation.SetFileCount(v)
	return _u
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_u *DuplicateGroupUpdate) SetNillableFileCount(v *int) *DuplicateGroupUpdate {
	if v != nil {
		_u.SetFileCount(*v)
	}
	return _u
}

// AddFileCount adds value to the "file_count" field.
func (_u *DuplicateGroupUpdate) AddFileCount(v int) *DuplicateGroupUpdate {
	_u.mutation.AddFileCount(v)
	return _u
}

// SetTotalSizeBytes sets the "total_size_bytes" field.
func (_u *DuplicateGroupUpdate) SetTotalSizeBytes(v int64) *DuplicateGroupUpdate {
	_u.mutation.ResetTotalSizeBytes()
	_u.mutation.SetTotalSizeBytes(v)
	return _u
}

// SetNillableTotalSizeBytes sets the "total_size_bytes" field if the given value is not nil.
func (_u *DuplicateGroupUpdate) SetNillableTotalSizeBytes(v *int64) *DuplicateGroupUpdate {
	if v != nil {
		_u.SetTotalSizeBytes(*v)
	}
	return _u
}

// AddTotalSizeBytes adds value to the "total_size_bytes" field.
func (_u *DuplicateGroupUpdate) AddTotalSizeBytes(v int64) *DuplicateGroupUpdate {
	_u.mutation.AddTotalSizeBytes(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *DuplicateGroupUpdate) SetTenant(v *Tenant) *DuplicateGroupUpdate {
	return _u.SetTenantID(v.ID)
}

// SetScan sets the "scan" edge to the Scan entity.
func (_u *DuplicateGroupUpdate) SetScan(v *Scan) *DuplicateGroupUpdate {
	return _u.SetScanID(v.ID)
}

// SetKeeperMachine sets the "keeper_machine" edge to the Machine entity.
func (_u *DuplicateGroupUpdate) SetKeeperMachine(v *Machine) *DuplicateGroupUpdate {
	return _u.SetKeeperMachineID(v.ID)
}

// AddFileInstanceIDs adds the "file_instances" edge to the FileInstance entity by IDs.
func (_u *DuplicateGroupUpdate) AddFileInstanceIDs(ids ...uuid.UUID) *DuplicateGroupUpdate {
	_u.mutation.AddFileInstanceIDs(ids...)
	return _u
}

// AddFileInstances adds the "file_instances" edges to the FileInstance entity.
func (_u *DuplicateGroupUpdate) AddFileInstances(v ...*FileInstance) *DuplicateGroupUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileInstanceIDs(ids...)
}

// AddActionAuditIDs adds the "action_audits" edge to the ActionAudit entity by IDs.
func (_u *DuplicateGroupUpdate) AddActionAuditIDs(ids ...uuid.UUID) *DuplicateGroupUpdate {
	_u.mutation.AddActionAuditIDs(ids...)
	return _u
}

// AddActionAudits adds the "action_audits" edges to the ActionAudit entity.
func (_u *DuplicateGroupUpdate) AddActionAudits(v ...*ActionAudit) *DuplicateGroupUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActionAuditIDs(ids...)
}

// Mutation returns the DuplicateGroupMutation object of the builder.
func (_u *DuplicateGroupUpdate) Mutation() *DuplicateGroupMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *DuplicateGroupUpdate) ClearTenant() *DuplicateGroupUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearScan clears the "scan" edge to the Scan entity.
func (_u *DuplicateGroupUpdate) ClearScan() *DuplicateGroupUpdate {
	_u.mutation.ClearScan()
	return _u
}

// ClearKeeperMachine clears the "keeper_machine" edge to the Machine entity.
func (_u *DuplicateGroupUpdate) ClearKeeperMachine() *DuplicateGroupUpdate {
	_u.mutation.ClearKeeperMachine()
	return _u
}

// ClearFileInstances clears all "file_instances" edges to the FileInstance entity.
func (_u *DuplicateGroupUpdate) ClearFileInstances() *DuplicateGroupUpdate {
	_u.mutation.ClearFileInstances()
	return _u
}

// RemoveFileInstanceIDs removes the "file_instances" edge to FileInstance entities by IDs.
func (_u *DuplicateGroupUpdate) RemoveFileInstanceIDs(ids ...uuid.UUID) *DuplicateGroupUpdate {
	_u.mutation.RemoveFileInstanceIDs(ids...)
	return _u
}

// RemoveFileInstances removes "file_instances" edges to FileInstance entities.
func (_u *DuplicateGroupUpdate) RemoveFileInstances(v ...*FileInstance) *DuplicateGroupUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileInstanceIDs(ids...)
}

// ClearActionAudits clears all "action_audits" edges to the ActionAudit entity.
func (_u *DuplicateGroupUpdate) ClearActionAudits() *DuplicateGroupUpdate {
	_u.mutation.ClearActionAudits()
	return _u
}

// RemoveActionAuditIDs removes the "action_audits" edge to ActionAudit entities by IDs.
func (_u *DuplicateGroupUpdate) RemoveActionAuditIDs(ids ...uuid.UUID) *DuplicateGroupUpdate {
	_u.mutation.RemoveActionAuditIDs(ids...)
	return _u
}

// RemoveActionAudits removes "action_audits" edges to ActionAudit entities.
func (_u *DuplicateGroupUpdate) RemoveActionAudits(v ...*ActionAudit) *DuplicateGroupUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActionAuditIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DuplicateGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DuplicateGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DuplicateGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DuplicateGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DuplicateGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := duplicategroup.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DuplicateGroupUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := duplicategroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DuplicateGroup.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileCount(); ok {
		if err := duplicategroup.FileCountValidator(v); err != nil {
			return &ValidationError{Name: "file_count", err: fmt.Errorf(`ent: validator failed for field "DuplicateGroup.file_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalSizeBytes(); ok {
		if err := duplicategroup.TotalSizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "total_size_bytes", err: fmt.Errorf(`ent: validator failed for field "DuplicateGroup.total_size_bytes": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DuplicateGroup.tenant"`)
	}
	if _u.mutation.ScanCleared() && len(_u.mutation.ScanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DuplicateGroup.scan"`)
	}
	return nil
}

func (_u *DuplicateGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(duplicategroup.Table, duplicategroup.Columns, sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(duplicategroup.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(duplicategroup.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(duplicategroup.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FileCount(); ok {
		_spec.SetField(duplicategroup.FieldFileCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFileCount(); ok {
		_spec.AddField(duplicategroup.FieldFileCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalSizeBytes(); ok {
		_spec.SetField(duplicategroup.FieldTotalSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalSizeBytes(); ok {
		_spec.AddField(duplicategroup.FieldTotalSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.TenantTable,
			Columns: []string{duplicategroup.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.TenantTable,
			Columns: []string{duplicategroup.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.ScanTable,
			Columns: []string{duplicategroup.ScanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.ScanTable,
			Columns: []string{duplicategroup.ScanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KeeperMachineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.KeeperMachineTable,
			Columns: []string{duplicategroup.KeeperMachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeeperMachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.KeeperMachineTable,
			Columns: []string{duplicategroup.KeeperMachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FileInstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.FileInstancesTable,
			Columns: []string{duplicategroup.FileInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileinstance.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFileInstancesIDs(); len(nodes) > 0 && !_u.mutation.FileInstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.FileInstancesTable,
			Columns: []string{duplicategroup.FileInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileinstance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FileInstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.FileInstancesTable,
			Columns: []string{duplicategroup.FileInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileinstance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActionAuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.ActionAuditsTable,
			Columns: []string{duplicategroup.ActionAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActionAuditsIDs(); len(nodes) > 0 && !_u.mutation.ActionAuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.ActionAuditsTable,
			Columns: []string{duplicategroup.ActionAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActionAuditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.ActionAuditsTable,
			Columns: []string{duplicategroup.ActionAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{duplicategroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DuplicateGroupUpdateOne is the builder for updating a single DuplicateGroup entity.
type DuplicateGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DuplicateGroupMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *DuplicateGroupUpdateOne) SetUpdateTime(v time.Time) *DuplicateGroupUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *DuplicateGroupUpdateOne) SetTenantID(v uuid.UUID) *DuplicateGroupUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *DuplicateGroupUpdateOne) SetNillableTenantID(v *uuid.UUID) *DuplicateGroupUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetScanID sets the "scan_id" field.
func (_u *DuplicateGroupUpdateOne) SetScanID(v uuid.UUID) *DuplicateGroupUpdateOne {
	_u.mutation.SetScanID(v)
	return _u
}

// SetNillableScanID sets the "scan_id" field if the given value is not nil.
func (_u *DuplicateGroupUpdateOne) SetNillableScanID(v *uuid.UUID) *DuplicateGroupUpdateOne {
	if v != nil {
		_u.SetScanID(*v)
	}
	return _u
}

// SetKeeperMachineID sets the "keeper_machine_id" field.
func (_u *DuplicateGroupUpdateOne) SetKeeperMachineID(v uuid.UUID) *DuplicateGroupUpdateOne {
	_u.mutation.SetKeeperMachineID(v)
	return _u
}

// SetNillableKeeperMachineID sets the "keeper_machine_id" field if the given value is not nil.
func (_u *DuplicateGroupUpdateOne) SetNillableKeeperMachineID(v *uuid.UUID) *DuplicateGroupUpdateOne {
	if v != nil {
		_u.SetKeeperMachineID(*v)
	}
	return _u
}

// ClearKeeperMachineID clears the value of the "keeper_machine_id" field.
func (_u *DuplicateGroupUpdateOne) ClearKeeperMachineID() *DuplicateGroupUpdateOne {
	_u.mutation.ClearKeeperMachineID()
	return _u
}

// SetHash sets the "hash" field.
func (_u *DuplicateGroupUpdateOne) SetHash(v string) *DuplicateGroupUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *DuplicateGroupUpdateOne) SetNillableHash(v *string) *DuplicateGroupUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DuplicateGroupUpdateOne) SetStatus(v duplicategroup.Status) *DuplicateGroupUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DuplicateGroupUpdateOne) SetNillableStatus(v *duplicategroup.Status) *DuplicateGroupUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFileCount sets the "file_count" field.
func (_u *DuplicateGroupUpdateOne) SetFileCount(v int) *DuplicateGroupUpdateOne {
	_u.mutation.ResetFileCount()
	_u.mutation.SetFileCount(v)
	return _u
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_u *DuplicateGroupUpdateOne) SetNillableFileCount(v *int) *DuplicateGroupUpdateOne {
	if v != nil {
		_u.SetFileCount(*v)
	}
	return _u
}

// AddFileCount adds value to the "file_count" field.
func (_u *DuplicateGroupUpdateOne) AddFileCount(v int) *DuplicateGroupUpdateOne {
	_u.mutation.AddFileCount(v)
	return _u
}

// SetTotalSizeBytes sets the "total_size_bytes" field.
func (_u *DuplicateGroupUpdateOne) SetTotalSizeBytes(v int64) *DuplicateGroupUpdateOne {
	_u.mutation.ResetTotalSizeBytes()
	_u.mutation.SetTotalSizeBytes(v)
	return _u
}

// SetNillableTotalSizeBytes sets the "total_size_bytes" field if the given value is not nil.
func (_u *DuplicateGroupUpdateOne) SetNillableTotalSizeBytes(v *int64) *DuplicateGroupUpdateOne {
	if v != nil {
		_u.SetTotalSizeBytes(*v)
	}
	return _u
}

// AddTotalSizeBytes adds value to the "total_size_bytes" field.
func (_u *DuplicateGroupUpdateOne) AddTotalSizeBytes(v int64) *DuplicateGroupUpdateOne {
	_u.mutation.AddTotalSizeBytes(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *DuplicateGroupUpdateOne) SetTenant(v *Tenant) *DuplicateGroupUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetScan sets the "scan" edge to the Scan entity.
func (_u *DuplicateGroupUpdateOne) SetScan(v *Scan) *DuplicateGroupUpdateOne {
	return _u.SetScanID(v.ID)
}

// SetKeeperMachine sets the "keeper_machine" edge to the Machine entity.
func (_u *DuplicateGroupUpdateOne) SetKeeperMachine(v *Machine) *DuplicateGroupUpdateOne {
	return _u.SetKeeperMachineID(v.ID)
}

// AddFileInstanceIDs adds the "file_instances" edge to the FileInstance entity by IDs.
func (_u *DuplicateGroupUpdateOne) AddFileInstanceIDs(ids ...uuid.UUID) *DuplicateGroupUpdateOne {
	_u.mutation.AddFileInstanceIDs(ids...)
	return _u
}

// AddFileInstances adds the "file_instances" edges to the FileInstance entity.
func (_u *DuplicateGroupUpdateOne) AddFileInstances(v ...*FileInstance) *DuplicateGroupUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileInstanceIDs(ids...)
}

// AddActionAuditIDs adds the "action_audits" edge to the ActionAudit entity by IDs.
func (_u *DuplicateGroupUpdateOne) AddActionAuditIDs(ids ...uuid.UUID) *DuplicateGroupUpdateOne {
	_u.mutation.AddActionAuditIDs(ids...)
	return _u
}

// AddActionAudits adds the "action_audits" edges to the ActionAudit entity.
func (_u *DuplicateGroupUpdateOne) AddActionAudits(v ...*ActionAudit) *DuplicateGroupUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddActionAuditIDs(ids...)
}

// Mutation returns the DuplicateGroupMutation object of the builder.
func (_u *DuplicateGroupUpdateOne) Mutation() *DuplicateGroupMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *DuplicateGroupUpdateOne) ClearTenant() *DuplicateGroupUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearScan clears the "scan" edge to the Scan entity.
func (_u *DuplicateGroupUpdateOne) ClearScan() *DuplicateGroupUpdateOne {
	_u.mutation.ClearScan()
	return _u
}

// ClearKeeperMachine clears the "keeper_machine" edge to the Machine entity.
func (_u *DuplicateGroupUpdateOne) ClearKeeperMachine() *DuplicateGroupUpdateOne {
	_u.mutation.ClearKeeperMachine()
	return _u
}

// ClearFileInstances clears all "file_instances" edges to the FileInstance entity.
func (_u *DuplicateGroupUpdateOne) ClearFileInstances() *DuplicateGroupUpdateOne {
	_u.mutation.ClearFileInstances()
	return _u
}

// RemoveFileInstanceIDs removes the "file_instances" edge to FileInstance entities by IDs.
func (_u *DuplicateGroupUpdateOne) RemoveFileInstanceIDs(ids ...uuid.UUID) *DuplicateGroupUpdateOne {
	_u.mutation.RemoveFileInstanceIDs(ids...)
	return _u
}

// RemoveFileInstances removes "file_instances" edges to FileInstance entities.
func (_u *DuplicateGroupUpdateOne) RemoveFileInstances(v ...*FileInstance) *DuplicateGroupUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileInstanceIDs(ids...)
}

// ClearActionAudits clears all "action_audits" edges to the ActionAudit entity.
func (_u *DuplicateGroupUpdateOne) ClearActionAudits() *DuplicateGroupUpdateOne {
	_u.mutation.ClearActionAudits()
	return _u
}

// RemoveActionAuditIDs removes the "action_audits" edge to ActionAudit entities by IDs.
func (_u *DuplicateGroupUpdateOne) RemoveActionAuditIDs(ids ...uuid.UUID) *DuplicateGroupUpdateOne {
	_u.mutation.RemoveActionAuditIDs(ids...)
	return _u
}

// RemoveActionAudits removes "action_audits" edges to ActionAudit entities.
func (_u *DuplicateGroupUpdateOne) RemoveActionAudits(v ...*ActionAudit) *DuplicateGroupUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveActionAuditIDs(ids...)
}

// Where appends a list predicates to the DuplicateGroupUpdate builder.
func (_u *DuplicateGroupUpdateOne) Where(ps ...predicate.DuplicateGroup) *DuplicateGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DuplicateGroupUpdateOne) Select(field string, fields ...string) *DuplicateGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DuplicateGroup entity.
func (_u *DuplicateGroupUpdateOne) Save(ctx context.Context) (*DuplicateGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DuplicateGroupUpdateOne) SaveX(ctx context.Context) *DuplicateGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DuplicateGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DuplicateGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DuplicateGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := duplicategroup.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DuplicateGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := duplicategroup.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DuplicateGroup.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileCount(); ok {
		if err := duplicategroup.FileCountValidator(v); err != nil {
			return &ValidationError{Name: "file_count", err: fmt.Errorf(`ent: validator failed for field "DuplicateGroup.file_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalSizeBytes(); ok {
		if err := duplicategroup.TotalSizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "total_size_bytes", err: fmt.Errorf(`ent: validator failed for field "DuplicateGroup.total_size_bytes": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DuplicateGroup.tenant"`)
	}
	if _u.mutation.ScanCleared() && len(_u.mutation.ScanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DuplicateGroup.scan"`)
	}
	return nil
}

func (_u *DuplicateGroupUpdateOne) sqlSave(ctx context.Context) (_node *DuplicateGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(duplicategroup.Table, duplicategroup.Columns, sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DuplicateGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, duplicategroup.FieldID)
		for _, f := range fields {
			if !duplicategroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != duplicategroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(duplicategroup.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(duplicategroup.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(duplicategroup.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FileCount(); ok {
		_spec.SetField(duplicategroup.FieldFileCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFileCount(); ok {
		_spec.AddField(duplicategroup.FieldFileCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalSizeBytes(); ok {
		_spec.SetField(duplicategroup.FieldTotalSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalSizeBytes(); ok {
		_spec.AddField(duplicategroup.FieldTotalSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.TenantTable,
			Columns: []string{duplicategroup.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.TenantTable,
			Columns: []string{duplicategroup.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.ScanTable,
			Columns: []string{duplicategroup.ScanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.ScanTable,
			Columns: []string{duplicategroup.ScanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KeeperMachineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.KeeperMachineTable,
			Columns: []string{duplicategroup.KeeperMachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeeperMachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   duplicategroup.KeeperMachineTable,
			Columns: []string{duplicategroup.KeeperMachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FileInstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.FileInstancesTable,
			Columns: []string{duplicategroup.FileInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileinstance.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFileInstancesIDs(); len(nodes) > 0 && !_u.mutation.FileInstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.FileInstancesTable,
			Columns: []string{duplicategroup.FileInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileinstance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FileInstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.FileInstancesTable,
			Columns: []string{duplicategroup.FileInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileinstance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ActionAuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.ActionAuditsTable,
			Columns: []string{duplicategroup.ActionAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedActionAuditsIDs(); len(nodes) > 0 && !_u.mutation.ActionAuditsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.ActionAuditsTable,
			Columns: []string{duplicategroup.ActionAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActionAuditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   duplicategroup.ActionAuditsTable,
			Columns: []string{duplicategroup.ActionAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionaudit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DuplicateGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{duplicategroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
