// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/actionaudit"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/fileinstance"
	"github.com/mcmx/duplynx/ent/machine"
	"github.com/mcmx/duplynx/ent/predicate"
	"github.com/mcmx/duplynx/ent/scan"
	"github.com/mcmx/duplynx/ent/tenant"
)

// DuplicateGroupQuery is the builder for querying DuplicateGroup entities.
type DuplicateGroupQuery struct {
	config
	ctx               *QueryContext
	order             []duplicategroup.OrderOption
	inters            []Interceptor
	predicates        []predicate.DuplicateGroup
	withTenant        *TenantQuery
	withScan          *ScanQuery
	withKeeperMachine *MachineQuery
	withFileInstances *FileInstanceQuery
	withActionAudits  *ActionAuditQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DuplicateGroupQuery builder.
func (_q *DuplicateGroupQuery) Where(ps ...predicate.DuplicateGroup) *DuplicateGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DuplicateGroupQuery) Limit(limit int) *DuplicateGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DuplicateGroupQuery) Offset(offset int) *DuplicateGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DuplicateGroupQuery) Unique(unique bool) *DuplicateGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DuplicateGroupQuery) Order(o ...duplicategroup.OrderOption) *DuplicateGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *DuplicateGroupQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, duplicategroup.TenantTable, duplicategroup.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScan chains the current query on the "scan" edge.
func (_q *DuplicateGroupQuery) QueryScan() *ScanQuery {
	query := (&ScanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, selector),
			sqlgraph.To(scan.Table, scan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, duplicategroup.ScanTable, duplicategroup.ScanColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryKeeperMachine chains the current query on the "keeper_machine" edge.
func (_q *DuplicateGroupQuery) QueryKeeperMachine() *MachineQuery {
	query := (&MachineClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, selector),
			sqlgraph.To(machine.Table, machine.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, duplicategroup.KeeperMachineTable, duplicategroup.KeeperMachineColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFileInstances chains the current query on the "file_instances" edge.
func (_q *DuplicateGroupQuery) QueryFileInstances() *FileInstanceQuery {
	query := (&FileInstanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, selector),
			sqlgraph.To(fileinstance.Table, fileinstance.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, duplicategroup.FileInstancesTable, duplicategroup.FileInstancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryActionAudits chains the current query on the "action_audits" edge.
func (_q *DuplicateGroupQuery) QueryActionAudits() *ActionAuditQuery {
	query := (&ActionAuditClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(duplicategroup.Table, duplicategroup.FieldID, selector),
			sqlgraph.To(actionaudit.Table, actionaudit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, duplicategroup.ActionAuditsTable, duplicategroup.ActionAuditsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DuplicateGroup entity from the query.
// Returns a *NotFoundError when no DuplicateGroup was found.
func (_q *DuplicateGroupQuery) First(ctx context.Context) (*DuplicateGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{duplicategroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DuplicateGroupQuery) FirstX(ctx context.Context) *DuplicateGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DuplicateGroup ID from the query.
// Returns a *NotFoundError when no DuplicateGroup ID was found.
func (_q *DuplicateGroupQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{duplicategroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DuplicateGroupQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DuplicateGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DuplicateGroup entity is found.
// Returns a *NotFoundError when no DuplicateGroup entities are found.
func (_q *DuplicateGroupQuery) Only(ctx context.Context) (*DuplicateGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{duplicategroup.Label}
	default:
		return nil, &NotSingularError{duplicategroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DuplicateGroupQuery) OnlyX(ctx context.Context) *DuplicateGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DuplicateGroup ID in the query.
// Returns a *NotSingularError when more than one DuplicateGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DuplicateGroupQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{duplicategroup.Label}
	default:
		err = &NotSingularError{duplicategroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DuplicateGroupQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DuplicateGroups.
func (_q *DuplicateGroupQuery) All(ctx context.Context) ([]*DuplicateGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DuplicateGroup, *DuplicateGroupQuery]()
	return withInterceptors[[]*DuplicateGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DuplicateGroupQuery) AllX(ctx context.Context) []*DuplicateGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DuplicateGroup IDs.
func (_q *DuplicateGroupQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(duplicategroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DuplicateGroupQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DuplicateGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DuplicateGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DuplicateGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DuplicateGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DuplicateGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DuplicateGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DuplicateGroupQuery) Clone() *DuplicateGroupQuery {
	if _q == nil {
		return nil
	}
	return &DuplicateGroupQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]duplicategroup.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.DuplicateGroup{}, _q.predicates...),
		withTenant:        _q.withTenant.Clone(),
		withScan:          _q.withScan.Clone(),
		withKeeperMachine: _q.withKeeperMachine.Clone(),
		withFileInstances: _q.withFileInstances.Clone(),
		withActionAudits:  _q.withActionAudits.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DuplicateGroupQuery) WithTenant(opts ...func(*TenantQuery)) *DuplicateGroupQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithScan tells the query-builder to eager-load the nodes that are connected to
// the "scan" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DuplicateGroupQuery) WithScan(opts ...func(*ScanQuery)) *DuplicateGroupQuery {
	query := (&ScanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withScan = query
	return _q
}

// WithKeeperMachine tells the query-builder to eager-load the nodes that are connected to
// the "keeper_machine" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DuplicateGroupQuery) WithKeeperMachine(opts ...func(*MachineQuery)) *DuplicateGroupQuery {
	query := (&MachineClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withKeeperMachine = query
	return _q
}

// WithFileInstances tells the query-builder to eager-load the nodes that are connected to
// the "file_instances" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DuplicateGroupQuery) WithFileInstances(opts ...func(*FileInstanceQuery)) *DuplicateGroupQuery {
	query := (&FileInstanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFileInstances = query
	return _q
}

// WithActionAudits tells the query-builder to eager-load the nodes that are connected to
// the "action_audits" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DuplicateGroupQuery) WithActionAudits(opts ...func(*ActionAuditQuery)) *DuplicateGroupQuery {
	query := (&ActionAuditClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withActionAudits = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DuplicateGroup.Query().
//		GroupBy(duplicategroup.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DuplicateGroupQuery) GroupBy(field string, fields ...string) *DuplicateGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DuplicateGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = duplicategroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.DuplicateGroup.Query().
//		Select(duplicategroup.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *DuplicateGroupQuery) Select(fields ...string) *DuplicateGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DuplicateGroupSelect{DuplicateGroupQuery: _q}
	sbuild.label = duplicategroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DuplicateGroupSelect configured with the given aggregations.
func (_q *DuplicateGroupQuery) Aggregate(fns ...AggregateFunc) *DuplicateGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DuplicateGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !duplicategroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DuplicateGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DuplicateGroup, error) {
	var (
		nodes       = []*DuplicateGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withTenant != nil,
			_q.withScan != nil,
			_q.withKeeperMachine != nil,
			_q.withFileInstances != nil,
			_q.withActionAudits != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DuplicateGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DuplicateGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *DuplicateGroup, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withScan; query != nil {
		if err := _q.loadScan(ctx, query, nodes, nil,
			func(n *DuplicateGroup, e *Scan) { n.Edges.Scan = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withKeeperMachine; query != nil {
		if err := _q.loadKeeperMachine(ctx, query, nodes, nil,
			func(n *DuplicateGroup, e *Machine) { n.Edges.KeeperMachine = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFileInstances; query != nil {
		if err := _q.loadFileInstances(ctx, query, nodes,
			func(n *DuplicateGroup) { n.Edges.FileInstances = []*FileInstance{} },
			func(n *DuplicateGroup, e *FileInstance) { n.Edges.FileInstances = append(n.Edges.FileInstances, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withActionAudits; query != nil {
		if err := _q.loadActionAudits(ctx, query, nodes,
			func(n *DuplicateGroup) { n.Edges.ActionAudits = []*ActionAudit{} },
			func(n *DuplicateGroup, e *ActionAudit) { n.Edges.ActionAudits = append(n.Edges.ActionAudits, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DuplicateGroupQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*DuplicateGroup, init func(*DuplicateGroup), assign func(*DuplicateGroup, *Tenant)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DuplicateGroup)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DuplicateGroupQuery) loadScan(ctx context.Context, query *ScanQuery, nodes []*DuplicateGroup, init func(*DuplicateGroup), assign func(*DuplicateGroup, *Scan)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DuplicateGroup)
	for i := range nodes {
		fk := nodes[i].ScanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(scan.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "scan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DuplicateGroupQuery) loadKeeperMachine(ctx context.Context, query *MachineQuery, nodes []*DuplicateGroup, init func(*DuplicateGroup), assign func(*DuplicateGroup, *Machine)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DuplicateGroup)
	for i := range nodes {
		fk := nodes[i].KeeperMachineID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(machine.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "keeper_machine_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DuplicateGroupQuery) loadFileInstances(ctx context.Context, query *FileInstanceQuery, nodes []*DuplicateGroup, init func(*DuplicateGroup), assign func(*DuplicateGroup, *FileInstance)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*DuplicateGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(fileinstance.FieldDuplicateGroupID)
	}
	query.Where(predicate.FileInstance(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(duplicategroup.FileInstancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DuplicateGroupID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "duplicate_group_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DuplicateGroupQuery) loadActionAudits(ctx context.Context, query *ActionAuditQuery, nodes []*DuplicateGroup, init func(*DuplicateGroup), assign func(*DuplicateGroup, *ActionAudit)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*DuplicateGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(actionaudit.FieldDuplicateGroupID)
	}
	query.Where(predicate.ActionAudit(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(duplicategroup.ActionAuditsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DuplicateGroupID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "duplicate_group_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DuplicateGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DuplicateGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(duplicategroup.Table, duplicategroup.Columns, sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, duplicategroup.FieldID)
		for i := range fields {
			if fields[i] != duplicategroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(duplicategroup.FieldTenantID)
		}
		if _q.withScan != nil {
			_spec.Node.AddColumnOnce(duplicategroup.FieldScanID)
		}
		if _q.withKeeperMachine != nil {
			_spec.Node.AddColumnOnce(duplicategroup.FieldKeeperMachineID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DuplicateGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(duplicategroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = duplicategroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DuplicateGroupGroupBy is the group-by builder for DuplicateGroup entities.
type DuplicateGroupGroupBy struct {
	selector
	build *DuplicateGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DuplicateGroupGroupBy) Aggregate(fns ...AggregateFunc) *DuplicateGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DuplicateGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DuplicateGroupQuery, *DuplicateGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DuplicateGroupGroupBy) sqlScan(ctx context.Context, root *DuplicateGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DuplicateGroupSelect is the builder for selecting fields of DuplicateGroup entities.
type DuplicateGroupSelect struct {
	*DuplicateGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DuplicateGroupSelect) Aggregate(fns ...AggregateFunc) *DuplicateGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DuplicateGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DuplicateGroupQuery, *DuplicateGroupSelect](ctx, _s.DuplicateGroupQuery, _s, _s.inters, v)
}

func (_s *DuplicateGroupSelect) sqlScan(ctx context.Context, root *DuplicateGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
