// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/fileinstance"
	"github.com/mcmx/duplynx/ent/machine"
)

// FileInstanceCreate is the builder for creating a FileInstance entity.
type FileInstanceCreate struct {
	config
	mutation *FileInstanceMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *FileInstanceCreate) SetCreateTime(v time.Time) *FileInstanceCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *FileInstanceCreate) SetNillableCreateTime(v *time.Time) *FileInstanceCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *FileInstanceCreate) SetUpdateTime(v time.Time) *FileInstanceCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *FileInstanceCreate) SetNillableUpdateTime(v *time.Time) *FileInstanceCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDuplicateGroupID sets the "duplicate_group_id" field.
func (_c *FileInstanceCreate) SetDuplicateGroupID(v uuid.UUID) *FileInstanceCreate {
	_c.mutation.SetDuplicateGroupID(v)
	return _c
}

// SetMachineID sets the "machine_id" field.
func (_c *FileInstanceCreate) SetMachineID(v uuid.UUID) *FileInstanceCreate {
	_c.mutation.SetMachineID(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *FileInstanceCreate) SetPath(v string) *FileInstanceCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *FileInstanceCreate) SetSizeBytes(v int64) *FileInstanceCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *FileInstanceCreate) SetChecksum(v string) *FileInstanceCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *FileInstanceCreate) SetLastSeenAt(v time.Time) *FileInstanceCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *FileInstanceCreate) SetNillableLastSeenAt(v *time.Time) *FileInstanceCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetQuarantined sets the "quarantined" field.
func (_c *FileInstanceCreate) SetQuarantined(v bool) *FileInstanceCreate {
	_c.mutation.SetQuarantined(v)
	return _c
}

// SetNillableQuarantined sets the "quarantined" field if the given value is not nil.
func (_c *FileInstanceCreate) SetNillableQuarantined(v *bool) *FileInstanceCreate {
	if v != nil {
		_c.SetQuarantined(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FileInstanceCreate) SetID(v uuid.UUID) *FileInstanceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FileInstanceCreate) SetNillableID(v *uuid.UUID) *FileInstanceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDuplicateGroup sets the "duplicate_group" edge to the DuplicateGroup entity.
func (_c *FileInstanceCreate) SetDuplicateGroup(v *DuplicateGroup) *FileInstanceCreate {
	return _c.SetDuplicateGroupID(v.ID)
}

// SetMachine sets the "machine" edge to the Machine entity.
func (_c *FileInstanceCreate) SetMachine(v *Machine) *FileInstanceCreate {
	return _c.SetMachineID(v.ID)
}

// Mutation returns the FileInstanceMutation object of the builder.
func (_c *FileInstanceCreate) Mutation() *FileInstanceMutation {
	return _c.mutation
}

// Save creates the FileInstance in the database.
func (_c *FileInstanceCreate) Save(ctx context.Context) (*FileInstance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileInstanceCreate) SaveX(ctx context.Context) *FileInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileInstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileInstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileInstanceCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := fileinstance.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := fileinstance.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := fileinstance.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
	if _, ok := _c.mutation.Quarantined(); !ok {
		v := fileinstance.DefaultQuarantined
		_c.mutation.SetQuarantined(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := fileinstance.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileInstanceCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "FileInstance.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "FileInstance.update_time"`)}
	}
	if _, ok := _c.mutation.DuplicateGroupID(); !ok {
		return &ValidationError{Name: "duplicate_group_id", err: errors.New(`ent: missing required field "FileInstance.duplicate_group_id"`)}
	}
	if _, ok := _c.mutation.MachineID(); !ok {
		return &ValidationError{Name: "machine_id", err: errors.New(`ent: missing required field "FileInstance.machine_id"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "FileInstance.path"`)}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "FileInstance.size_bytes"`)}
	}
	if v, ok := _c.mutation.SizeBytes(); ok {
		if err := fileinstance.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "FileInstance.size_bytes": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "FileInstance.checksum"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "FileInstance.last_seen_at"`)}
	}
	if _, ok := _c.mutation.Quarantined(); !ok {
		return &ValidationError{Name: "quarantined", err: errors.New(`ent: missing required field "FileInstance.quarantined"`)}
	}
	if len(_c.mutation.DuplicateGroupIDs()) == 0 {
		return &ValidationError{Name: "duplicate_group", err: errors.New(`ent: missing required edge "FileInstance.duplicate_group"`)}
	}
	if len(_c.mutation.MachineIDs()) == 0 {
		return &ValidationError{Name: "machine", err: errors.New(`ent: missing required edge "FileInstance.machine"`)}
	}
	return nil
}

func (_c *FileInstanceCreate) sqlSave(ctx context.Context) (*FileInstance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileInstanceCreate) createSpec() (*FileInstance, *sqlgraph.CreateSpec) {
	var (
		_node = &FileInstance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fileinstance.Table, sqlgraph.NewFieldSpec(fileinstance.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(fileinstance.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(fileinstance.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(fileinstance.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(fileinstance.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(fileinstance.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(fileinstance.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.Quarantined(); ok {
		_spec.SetField(fileinstance.FieldQuarantined, field.TypeBool, value)
		_node.Quarantined = value
	}
	if nodes := _c.mutation.DuplicateGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileinstance.DuplicateGroupTable,
			Columns: []string{fileinstance.DuplicateGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DuplicateGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileinstance.MachineTable,
			Columns: []string{fileinstance.MachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MachineID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileInstanceCreateBulk is the builder for creating many FileInstance entities in bulk.
type FileInstanceCreateBulk struct {
	config
	err      error
	builders []*FileInstanceCreate
}

// Save creates the FileInstance entities in the database.
func (_c *FileInstanceCreateBulk) Save(ctx context.Context) ([]*FileInstance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileInstance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileInstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileInstanceCreateBulk) SaveX(ctx context.Context) []*FileInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileInstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileInstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
