// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/fileinstance"
	"github.com/mcmx/duplynx/ent/machine"
)

// FileInstance is the model entity for the FileInstance schema.
type FileInstance struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// DuplicateGroupID holds the value of the "duplicate_group_id" field.
	DuplicateGroupID uuid.UUID `json:"duplicate_group_id,omitempty"`
	// MachineID holds the value of the "machine_id" field.
	MachineID uuid.UUID `json:"machine_id,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// Checksum holds the value of the "checksum" field.
	Checksum string `json:"checksum,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// Quarantined holds the value of the "quarantined" field.
	Quarantined bool `json:"quarantined,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FileInstanceQuery when eager-loading is set.
	Edges        FileInstanceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FileInstanceEdges holds the relations/edges for other nodes in the graph.
type FileInstanceEdges struct {
	// DuplicateGroup holds the value of the duplicate_group edge.
	DuplicateGroup *DuplicateGroup `json:"duplicate_group,omitempty"`
	// Machine holds the value of the machine edge.
	Machine *Machine `json:"machine,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DuplicateGroupOrErr returns the DuplicateGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FileInstanceEdges) DuplicateGroupOrErr() (*DuplicateGroup, error) {
	if e.DuplicateGroup != nil {
		return e.DuplicateGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: duplicategroup.Label}
	}
	return nil, &NotLoadedError{edge: "duplicate_group"}
}

// MachineOrErr returns the Machine value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FileInstanceEdges) MachineOrErr() (*Machine, error) {
	if e.Machine != nil {
		return e.Machine, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: machine.Label}
	}
	return nil, &NotLoadedError{edge: "machine"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FileInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fileinstance.FieldQuarantined:
			values[i] = new(sql.NullBool)
		case fileinstance.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case fileinstance.FieldPath, fileinstance.FieldChecksum:
			values[i] = new(sql.NullString)
		case fileinstance.FieldCreateTime, fileinstance.FieldUpdateTime, fileinstance.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		case fileinstance.FieldID, fileinstance.FieldDuplicateGroupID, fileinstance.FieldMachineID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FileInstance fields.
func (_m *FileInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fileinstance.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case fileinstance.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case fileinstance.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case fileinstance.FieldDuplicateGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_group_id", values[i])
			} else if value != nil {
				_m.DuplicateGroupID = *value
			}
		case fileinstance.FieldMachineID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field machine_id", values[i])
			} else if value != nil {
				_m.MachineID = *value
			}
		case fileinstance.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case fileinstance.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case fileinstance.FieldChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value.Valid {
				_m.Checksum = value.String
			}
		case fileinstance.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case fileinstance.FieldQuarantined:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field quarantined", values[i])
			} else if value.Valid {
				_m.Quarantined = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FileInstance.
// This includes values selected through modifiers, order, etc.
func (_m *FileInstance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDuplicateGroup queries the "duplicate_group" edge of the FileInstance entity.
func (_m *FileInstance) QueryDuplicateGroup() *DuplicateGroupQuery {
	return NewFileInstanceClient(_m.config).QueryDuplicateGroup(_m)
}

// QueryMachine queries the "machine" edge of the FileInstance entity.
func (_m *FileInstance) QueryMachine() *MachineQuery {
	return NewFileInstanceClient(_m.config).QueryMachine(_m)
}

// Update returns a builder for updating this FileInstance.
// Note that you need to call FileInstance.Unwrap() before calling this method if this FileInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FileInstance) Update() *FileInstanceUpdateOne {
	return NewFileInstanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FileInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FileInstance) Unwrap() *FileInstance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FileInstance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FileInstance) String() string {
	var builder strings.Builder
	builder.WriteString("FileInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("duplicate_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DuplicateGroupID))
	builder.WriteString(", ")
	builder.WriteString("machine_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MachineID))
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("checksum=")
	builder.WriteString(_m.Checksum)
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("quarantined=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quarantined))
	builder.WriteByte(')')
	return builder.String()
}

// FileInstances is a parsable slice of FileInstance.
type FileInstances []*FileInstance
