// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/fileinstance"
	"github.com/mcmx/duplynx/ent/machine"
	"github.com/mcmx/duplynx/ent/scan"
	"github.com/mcmx/duplynx/ent/tenant"
)

// MachineCreate is the builder for creating a Machine entity.
type MachineCreate struct {
	config
	mutation *MachineMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *MachineCreate) SetCreateTime(v time.Time) *MachineCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *MachineCreate) SetNillableCreateTime(v *time.Time) *MachineCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *MachineCreate) SetUpdateTime(v time.Time) *MachineCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *MachineCreate) SetNillableUpdateTime(v *time.Time) *MachineCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *MachineCreate) SetTenantID(v uuid.UUID) *MachineCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *MachineCreate) SetName(v string) *MachineCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *MachineCreate) SetCategory(v machine.Category) *MachineCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetHostname sets the "hostname" field.
func (_c *MachineCreate) SetHostname(v string) *MachineCreate {
	_c.mutation.SetHostname(v)
	return _c
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_c *MachineCreate) SetNillableHostname(v *string) *MachineCreate {
	if v != nil {
		_c.SetHostname(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *MachineCreate) SetRole(v string) *MachineCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *MachineCreate) SetNillableRole(v *string) *MachineCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetLastScanAt sets the "last_scan_at" field.
func (_c *MachineCreate) SetLastScanAt(v time.Time) *MachineCreate {
	_c.mutation.SetLastScanAt(v)
	return _c
}

// SetNillableLastScanAt sets the "last_scan_at" field if the given value is not nil.
func (_c *MachineCreate) SetNillableLastScanAt(v *time.Time) *MachineCreate {
	if v != nil {
		_c.SetLastScanAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MachineCreate) SetID(v uuid.UUID) *MachineCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MachineCreate) SetNillableID(v *uuid.UUID) *MachineCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *MachineCreate) SetTenant(v *Tenant) *MachineCreate {
	return _c.SetTenantID(v.ID)
}

// AddKeeperGroupIDs adds the "keeper_groups" edge to the DuplicateGroup entity by IDs.
func (_c *MachineCreate) AddKeeperGroupIDs(ids ...uuid.UUID) *MachineCreate {
	_c.mutation.AddKeeperGroupIDs(ids...)
	return _c
}

// AddKeeperGroups adds the "keeper_groups" edges to the DuplicateGroup entity.
func (_c *MachineCreate) AddKeeperGroups(v ...*DuplicateGroup) *MachineCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddKeeperGroupIDs(ids...)
}

// AddFileInstanceIDs adds the "file_instances" edge to the FileInstance entity by IDs.
func (_c *MachineCreate) AddFileInstanceIDs(ids ...uuid.UUID) *MachineCreate {
	_c.mutation.AddFileInstanceIDs(ids...)
	return _c
}

// AddFileInstances adds the "file_instances" edges to the FileInstance entity.
func (_c *MachineCreate) AddFileInstances(v ...*FileInstance) *MachineCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFileInstanceIDs(ids...)
}

// AddInitiatedScanIDs adds the "initiated_scans" edge to the Scan entity by IDs.
func (_c *MachineCreate) AddInitiatedScanIDs(ids ...uuid.UUID) *MachineCreate {
	_c.mutation.AddInitiatedScanIDs(ids...)
	return _c
}

// AddInitiatedScans adds the "initiated_scans" edges to the Scan entity.
func (_c *MachineCreate) AddInitiatedScans(v ...*Scan) *MachineCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInitiatedScanIDs(ids...)
}

// Mutation returns the MachineMutation object of the builder.
func (_c *MachineCreate) Mutation() *MachineMutation {
	return _c.mutation
}

// Save creates the Machine in the database.
func (_c *MachineCreate) Save(ctx context.Context) (*Machine, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MachineCreate) SaveX(ctx context.Context) *Machine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MachineCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MachineCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MachineCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := machine.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := machine.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := machine.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MachineCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Machine.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Machine.update_time"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Machine.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Machine.name"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Machine.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := machine.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Machine.category": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Machine.tenant"`)}
	}
	return nil
}

func (_c *MachineCreate) sqlSave(ctx context.Context) (*Machine, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MachineCreate) createSpec() (*Machine, *sqlgraph.CreateSpec) {
	var (
		_node = &Machine{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(machine.Table, sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(machine.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(machine.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(machine.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(machine.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Hostname(); ok {
		_spec.SetField(machine.FieldHostname, field.TypeString, value)
		_node.Hostname = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(machine.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.LastScanAt(); ok {
		_spec.SetField(machine.FieldLastScanAt, field.TypeTime, value)
		_node.LastScanAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   machine.TenantTable,
			Columns: []string{machine.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.KeeperGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   machine.KeeperGroupsTable,
			Columns: []string{machine.KeeperGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FileInstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   machine.FileInstancesTable,
			Columns: []string{machine.FileInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileinstance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InitiatedScansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   machine.InitiatedScansTable,
			Columns: []string{machine.InitiatedScansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MachineCreateBulk is the builder for creating many Machine entities in bulk.
type MachineCreateBulk struct {
	config
	err      error
	builders []*MachineCreate
}

// Save creates the Machine entities in the database.
func (_c *MachineCreateBulk) Save(ctx context.Context) ([]*Machine, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Machine, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MachineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MachineCreateBulk) SaveX(ctx context.Context) []*Machine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MachineCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MachineCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
