// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/machine"
	"github.com/mcmx/duplynx/ent/tenant"
)

// Machine is the model entity for the Machine schema.
type Machine struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Category holds the value of the "category" field.
	Category machine.Category `json:"category,omitempty"`
	// Hostname holds the value of the "hostname" field.
	Hostname string `json:"hostname,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// LastScanAt holds the value of the "last_scan_at" field.
	LastScanAt time.Time `json:"last_scan_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MachineQuery when eager-loading is set.
	Edges        MachineEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MachineEdges holds the relations/edges for other nodes in the graph.
type MachineEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// KeeperGroups holds the value of the keeper_groups edge.
	KeeperGroups []*DuplicateGroup `json:"keeper_groups,omitempty"`
	// FileInstances holds the value of the file_instances edge.
	FileInstances []*FileInstance `json:"file_instances,omitempty"`
	// InitiatedScans holds the value of the initiated_scans edge.
	InitiatedScans []*Scan `json:"initiated_scans,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MachineEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// KeeperGroupsOrErr returns the KeeperGroups value or an error if the edge
// was not loaded in eager-loading.
func (e MachineEdges) KeeperGroupsOrErr() ([]*DuplicateGroup, error) {
	if e.loadedTypes[1] {
		return e.KeeperGroups, nil
	}
	return nil, &NotLoadedError{edge: "keeper_groups"}
}

// FileInstancesOrErr returns the FileInstances value or an error if the edge
// was not loaded in eager-loading.
func (e MachineEdges) FileInstancesOrErr() ([]*FileInstance, error) {
	if e.loadedTypes[2] {
		return e.FileInstances, nil
	}
	return nil, &NotLoadedError{edge: "file_instances"}
}

// InitiatedScansOrErr returns the InitiatedScans value or an error if the edge
// was not loaded in eager-loading.
func (e MachineEdges) InitiatedScansOrErr() ([]*Scan, error) {
	if e.loadedTypes[3] {
		return e.InitiatedScans, nil
	}
	return nil, &NotLoadedError{edge: "initiated_scans"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Machine) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case machine.FieldName, machine.FieldCategory, machine.FieldHostname, machine.FieldRole:
			values[i] = new(sql.NullString)
		case machine.FieldCreateTime, machine.FieldUpdateTime, machine.FieldLastScanAt:
			values[i] = new(sql.NullTime)
		case machine.FieldID, machine.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Machine fields.
func (_m *Machine) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case machine.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case machine.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case machine.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case machine.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case machine.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case machine.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = machine.Category(value.String)
			}
		case machine.FieldHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostname", values[i])
			} else if value.Valid {
				_m.Hostname = value.String
			}
		case machine.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case machine.FieldLastScanAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_scan_at", values[i])
			} else if value.Valid {
				_m.LastScanAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Machine.
// This includes values selected through modifiers, order, etc.
func (_m *Machine) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Machine entity.
func (_m *Machine) QueryTenant() *TenantQuery {
	return NewMachineClient(_m.config).QueryTenant(_m)
}

// QueryKeeperGroups queries the "keeper_groups" edge of the Machine entity.
func (_m *Machine) QueryKeeperGroups() *DuplicateGroupQuery {
	return NewMachineClient(_m.config).QueryKeeperGroups(_m)
}

// QueryFileInstances queries the "file_instances" edge of the Machine entity.
func (_m *Machine) QueryFileInstances() *FileInstanceQuery {
	return NewMachineClient(_m.config).QueryFileInstances(_m)
}

// QueryInitiatedScans queries the "initiated_scans" edge of the Machine entity.
func (_m *Machine) QueryInitiatedScans() *ScanQuery {
	return NewMachineClient(_m.config).QueryInitiatedScans(_m)
}

// Update returns a builder for updating this Machine.
// Note that you need to call Machine.Unwrap() before calling this method if this Machine
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Machine) Update() *MachineUpdateOne {
	return NewMachineClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Machine entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Machine) Unwrap() *Machine {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Machine is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Machine) String() string {
	var builder strings.Builder
	builder.WriteString("Machine(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", _m.Category))
	builder.WriteString(", ")
	builder.WriteString("hostname=")
	builder.WriteString(_m.Hostname)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("last_scan_at=")
	builder.WriteString(_m.LastScanAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Machines is a parsable slice of Machine.
type Machines []*Machine
