// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/machine"
	"github.com/mcmx/duplynx/ent/scan"
	"github.com/mcmx/duplynx/ent/tenant"
)

// Scan is the model entity for the Scan schema.
type Scan struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// InitiatedMachineID holds the value of the "initiated_machine_id" field.
	InitiatedMachineID uuid.UUID `json:"initiated_machine_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// DuplicateGroupCount holds the value of the "duplicate_group_count" field.
	DuplicateGroupCount int `json:"duplicate_group_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScanQuery when eager-loading is set.
	Edges        ScanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScanEdges holds the relations/edges for other nodes in the graph.
type ScanEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// InitiatedMachine holds the value of the initiated_machine edge.
	InitiatedMachine *Machine `json:"initiated_machine,omitempty"`
	// DuplicateGroups holds the value of the duplicate_groups edge.
	DuplicateGroups []*DuplicateGroup `json:"duplicate_groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScanEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// InitiatedMachineOrErr returns the InitiatedMachine value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScanEdges) InitiatedMachineOrErr() (*Machine, error) {
	if e.InitiatedMachine != nil {
		return e.InitiatedMachine, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: machine.Label}
	}
	return nil, &NotLoadedError{edge: "initiated_machine"}
}

// DuplicateGroupsOrErr returns the DuplicateGroups value or an error if the edge
// was not loaded in eager-loading.
func (e ScanEdges) DuplicateGroupsOrErr() ([]*DuplicateGroup, error) {
	if e.loadedTypes[2] {
		return e.DuplicateGroups, nil
	}
	return nil, &NotLoadedError{edge: "duplicate_groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Scan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scan.FieldDuplicateGroupCount:
			values[i] = new(sql.NullInt64)
		case scan.FieldName, scan.FieldDescription:
			values[i] = new(sql.NullString)
		case scan.FieldCreateTime, scan.FieldUpdateTime, scan.FieldStartedAt, scan.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case scan.FieldID, scan.FieldTenantID, scan.FieldInitiatedMachineID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Scan fields.
func (_m *Scan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scan.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case scan.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case scan.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case scan.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case scan.FieldInitiatedMachineID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field initiated_machine_id", values[i])
			} else if value != nil {
				_m.InitiatedMachineID = *value
			}
		case scan.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case scan.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case scan.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case scan.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Time
			}
		case scan.FieldDuplicateGroupCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duplicate_group_count", values[i])
			} else if value.Valid {
				_m.DuplicateGroupCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Scan.
// This includes values selected through modifiers, order, etc.
func (_m *Scan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Scan entity.
func (_m *Scan) QueryTenant() *TenantQuery {
	return NewScanClient(_m.config).QueryTenant(_m)
}

// QueryInitiatedMachine queries the "initiated_machine" edge of the Scan entity.
func (_m *Scan) QueryInitiatedMachine() *MachineQuery {
	return NewScanClient(_m.config).QueryInitiatedMachine(_m)
}

// QueryDuplicateGroups queries the "duplicate_groups" edge of the Scan entity.
func (_m *Scan) QueryDuplicateGroups() *DuplicateGroupQuery {
	return NewScanClient(_m.config).QueryDuplicateGroups(_m)
}

// Update returns a builder for updating this Scan.
// Note that you need to call Scan.Unwrap() before calling this method if this Scan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Scan) Update() *ScanUpdateOne {
	return NewScanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Scan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Scan) Unwrap() *Scan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Scan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Scan) String() string {
	var builder strings.Builder
	builder.WriteString("Scan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("initiated_machine_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InitiatedMachineID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(_m.CompletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("duplicate_group_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DuplicateGroupCount))
	builder.WriteByte(')')
	return builder.String()
}

// Scans is a parsable slice of Scan.
type Scans []*Scan
