// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/duplicategroup"
	"github.com/mcmx/duplynx/ent/machine"
	"github.com/mcmx/duplynx/ent/predicate"
	"github.com/mcmx/duplynx/ent/scan"
	"github.com/mcmx/duplynx/ent/tenant"
)

// ScanUpdate is the builder for updating Scan entities.
type ScanUpdate struct {
	config
	hooks    []Hook
	mutation *ScanMutation
}

// Where appends a list predicates to the ScanUpdate builder.
func (_u *ScanUpdate) Where(ps ...predicate.Scan) *ScanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ScanUpdate) SetUpdateTime(v time.Time) *ScanUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ScanUpdate) SetTenantID(v uuid.UUID) *ScanUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ScanUpdate) SetNillableTenantID(v *uuid.UUID) *ScanUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetInitiatedMachineID sets the "initiated_machine_id" field.
func (_u *ScanUpdate) SetInitiatedMachineID(v uuid.UUID) *ScanUpdate {
	_u.mutation.SetInitiatedMachineID(v)
	return _u
}

// SetNillableInitiatedMachineID sets the "initiated_machine_id" field if the given value is not nil.
func (_u *ScanUpdate) SetNillableInitiatedMachineID(v *uuid.UUID) *ScanUpdate {
	if v != nil {
		_u.SetInitiatedMachineID(*v)
	}
	return _u
}

// ClearInitiatedMachineID clears the value of the "initiated_machine_id" field.
func (_u *ScanUpdate) ClearInitiatedMachineID() *ScanUpdate {
	_u.mutation.ClearInitiatedMachineID()
	return _u
}

// SetName sets the "name" field.
func (_u *ScanUpdate) SetName(v string) *ScanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScanUpdate) SetNillableName(v *string) *ScanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScanUpdate) SetDescription(v string) *ScanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScanUpdate) SetNillableDescription(v *string) *ScanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScanUpdate) ClearDescription() *ScanUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ScanUpdate) SetStartedAt(v time.Time) *ScanUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ScanUpdate) SetNillableStartedAt(v *time.Time) *ScanUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ScanUpdate) SetCompletedAt(v time.Time) *ScanUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ScanUpdate) SetNillableCompletedAt(v *time.Time) *ScanUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ScanUpdate) ClearCompletedAt() *ScanUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDuplicateGroupCount sets the "duplicate_group_count" field.
func (_u *ScanUpdate) SetDuplicateGroupCount(v int) *ScanUpdate {
	_u.mutation.ResetDuplicateGroupCount()
	_u.mutation.SetDuplicateGroupCount(v)
	return _u
}

// SetNillableDuplicateGroupCount sets the "duplicate_group_count" field if the given value is not nil.
func (_u *ScanUpdate) SetNillableDuplicateGroupCount(v *int) *ScanUpdate {
	if v != nil {
		_u.SetDuplicateGroupCount(*v)
	}
	return _u
}

// AddDuplicateGroupCount adds value to the "duplicate_group_count" field.
func (_u *ScanUpdate) AddDuplicateGroupCount(v int) *ScanUpdate {
	_u.mutation.AddDuplicateGroupCount(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *ScanUpdate) SetTenant(v *Tenant) *ScanUpdate {
	return _u.SetTenantID(v.ID)
}

// SetInitiatedMachine sets the "initiated_machine" edge to the Machine entity.
func (_u *ScanUpdate) SetInitiatedMachine(v *Machine) *ScanUpdate {
	return _u.SetInitiatedMachineID(v.ID)
}

// AddDuplicateGroupIDs adds the "duplicate_groups" edge to the DuplicateGroup entity by IDs.
func (_u *ScanUpdate) AddDuplicateGroupIDs(ids ...uuid.UUID) *ScanUpdate {
	_u.mutation.AddDuplicateGroupIDs(ids...)
	return _u
}

// AddDuplicateGroups adds the "duplicate_groups" edges to the DuplicateGroup entity.
func (_u *ScanUpdate) AddDuplicateGroups(v ...*DuplicateGroup) *ScanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDuplicateGroupIDs(ids...)
}

// Mutation returns the ScanMutation object of the builder.
func (_u *ScanUpdate) Mutation() *ScanMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *ScanUpdate) ClearTenant() *ScanUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearInitiatedMachine clears the "initiated_machine" edge to the Machine entity.
func (_u *ScanUpdate) ClearInitiatedMachine() *ScanUpdate {
	_u.mutation.ClearInitiatedMachine()
	return _u
}

// ClearDuplicateGroups clears all "duplicate_groups" edges to the DuplicateGroup entity.
func (_u *ScanUpdate) ClearDuplicateGroups() *ScanUpdate {
	_u.mutation.ClearDuplicateGroups()
	return _u
}

// RemoveDuplicateGroupIDs removes the "duplicate_groups" edge to DuplicateGroup entities by IDs.
func (_u *ScanUpdate) RemoveDuplicateGroupIDs(ids ...uuid.UUID) *ScanUpdate {
	_u.mutation.RemoveDuplicateGroupIDs(ids...)
	return _u
}

// RemoveDuplicateGroups removes "duplicate_groups" edges to DuplicateGroup entities.
func (_u *ScanUpdate) RemoveDuplicateGroups(v ...*DuplicateGroup) *ScanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDuplicateGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScanUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := scan.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScanUpdate) check() error {
	if v, ok := _u.mutation.DuplicateGroupCount(); ok {
		if err := scan.DuplicateGroupCountValidator(v); err != nil {
			return &ValidationError{Name: "duplicate_group_count", err: fmt.Errorf(`ent: validator failed for field "Scan.duplicate_group_count": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Scan.tenant"`)
	}
	return nil
}

func (_u *ScanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scan.Table, scan.Columns, sqlgraph.NewFieldSpec(scan.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(scan.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(scan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(scan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(scan.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(scan.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(scan.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DuplicateGroupCount(); ok {
		_spec.SetField(scan.FieldDuplicateGroupCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuplicateGroupCount(); ok {
		_spec.AddField(scan.FieldDuplicateGroupCount, field.TypeInt, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scan.TenantTable,
			Columns: []string{scan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scan.TenantTable,
			Columns: []string{scan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InitiatedMachineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scan.InitiatedMachineTable,
			Columns: []string{scan.InitiatedMachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InitiatedMachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scan.InitiatedMachineTable,
			Columns: []string{scan.InitiatedMachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DuplicateGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scan.DuplicateGroupsTable,
			Columns: []string{scan.DuplicateGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDuplicateGroupsIDs(); len(nodes) > 0 && !_u.mutation.DuplicateGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scan.DuplicateGroupsTable,
			Columns: []string{scan.DuplicateGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DuplicateGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scan.DuplicateGroupsTable,
			Columns: []string{scan.DuplicateGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScanUpdateOne is the builder for updating a single Scan entity.
type ScanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScanMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ScanUpdateOne) SetUpdateTime(v time.Time) *ScanUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ScanUpdateOne) SetTenantID(v uuid.UUID) *ScanUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ScanUpdateOne) SetNillableTenantID(v *uuid.UUID) *ScanUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetInitiatedMachineID sets the "initiated_machine_id" field.
func (_u *ScanUpdateOne) SetInitiatedMachineID(v uuid.UUID) *ScanUpdateOne {
	_u.mutation.SetInitiatedMachineID(v)
	return _u
}

// SetNillableInitiatedMachineID sets the "initiated_machine_id" field if the given value is not nil.
func (_u *ScanUpdateOne) SetNillableInitiatedMachineID(v *uuid.UUID) *ScanUpdateOne {
	if v != nil {
		_u.SetInitiatedMachineID(*v)
	}
	return _u
}

// ClearInitiatedMachineID clears the value of the "initiated_machine_id" field.
func (_u *ScanUpdateOne) ClearInitiatedMachineID() *ScanUpdateOne {
	_u.mutation.ClearInitiatedMachineID()
	return _u
}

// SetName sets the "name" field.
func (_u *ScanUpdateOne) SetName(v string) *ScanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScanUpdateOne) SetNillableName(v *string) *ScanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScanUpdateOne) SetDescription(v string) *ScanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScanUpdateOne) SetNillableDescription(v *string) *ScanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScanUpdateOne) ClearDescription() *ScanUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ScanUpdateOne) SetStartedAt(v time.Time) *ScanUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ScanUpdateOne) SetNillableStartedAt(v *time.Time) *ScanUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ScanUpdateOne) SetCompletedAt(v time.Time) *ScanUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ScanUpdateOne) SetNillableCompletedAt(v *time.Time) *ScanUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ScanUpdateOne) ClearCompletedAt() *ScanUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDuplicateGroupCount sets the "duplicate_group_count" field.
func (_u *ScanUpdateOne) SetDuplicateGroupCount(v int) *ScanUpdateOne {
	_u.mutation.ResetDuplicateGroupCount()
	_u.mutation.SetDuplicateGroupCount(v)
	return _u
}

// SetNillableDuplicateGroupCount sets the "duplicate_group_count" field if the given value is not nil.
func (_u *ScanUpdateOne) SetNillableDuplicateGroupCount(v *int) *ScanUpdateOne {
	if v != nil {
		_u.SetDuplicateGroupCount(*v)
	}
	return _u
}

// AddDuplicateGroupCount adds value to the "duplicate_group_count" field.
func (_u *ScanUpdateOne) AddDuplicateGroupCount(v int) *ScanUpdateOne {
	_u.mutation.AddDuplicateGroupCount(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *ScanUpdateOne) SetTenant(v *Tenant) *ScanUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetInitiatedMachine sets the "initiated_machine" edge to the Machine entity.
func (_u *ScanUpdateOne) SetInitiatedMachine(v *Machine) *ScanUpdateOne {
	return _u.SetInitiatedMachineID(v.ID)
}

// AddDuplicateGroupIDs adds the "duplicate_groups" edge to the DuplicateGroup entity by IDs.
func (_u *ScanUpdateOne) AddDuplicateGroupIDs(ids ...uuid.UUID) *ScanUpdateOne {
	_u.mutation.AddDuplicateGroupIDs(ids...)
	return _u
}

// AddDuplicateGroups adds the "duplicate_groups" edges to the DuplicateGroup entity.
func (_u *ScanUpdateOne) AddDuplicateGroups(v ...*DuplicateGroup) *ScanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDuplicateGroupIDs(ids...)
}

// Mutation returns the ScanMutation object of the builder.
func (_u *ScanUpdateOne) Mutation() *ScanMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *ScanUpdateOne) ClearTenant() *ScanUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearInitiatedMachine clears the "initiated_machine" edge to the Machine entity.
func (_u *ScanUpdateOne) ClearInitiatedMachine() *ScanUpdateOne {
	_u.mutation.ClearInitiatedMachine()
	return _u
}

// ClearDuplicateGroups clears all "duplicate_groups" edges to the DuplicateGroup entity.
func (_u *ScanUpdateOne) ClearDuplicateGroups() *ScanUpdateOne {
	_u.mutation.ClearDuplicateGroups()
	return _u
}

// RemoveDuplicateGroupIDs removes the "duplicate_groups" edge to DuplicateGroup entities by IDs.
func (_u *ScanUpdateOne) RemoveDuplicateGroupIDs(ids ...uuid.UUID) *ScanUpdateOne {
	_u.mutation.RemoveDuplicateGroupIDs(ids...)
	return _u
}

// RemoveDuplicateGroups removes "duplicate_groups" edges to DuplicateGroup entities.
func (_u *ScanUpdateOne) RemoveDuplicateGroups(v ...*DuplicateGroup) *ScanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDuplicateGroupIDs(ids...)
}

// Where appends a list predicates to the ScanUpdate builder.
func (_u *ScanUpdateOne) Where(ps ...predicate.Scan) *ScanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScanUpdateOne) Select(field string, fields ...string) *ScanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Scan entity.
func (_u *ScanUpdateOne) Save(ctx context.Context) (*Scan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScanUpdateOne) SaveX(ctx context.Context) *Scan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := scan.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScanUpdateOne) check() error {
	if v, ok := _u.mutation.DuplicateGroupCount(); ok {
		if err := scan.DuplicateGroupCountValidator(v); err != nil {
			return &ValidationError{Name: "duplicate_group_count", err: fmt.Errorf(`ent: validator failed for field "Scan.duplicate_group_count": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Scan.tenant"`)
	}
	return nil
}

func (_u *ScanUpdateOne) sqlSave(ctx context.Context) (_node *Scan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scan.Table, scan.Columns, sqlgraph.NewFieldSpec(scan.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Scan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scan.FieldID)
		for _, f := range fields {
			if !scan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(scan.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(scan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(scan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(scan.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(scan.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(scan.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DuplicateGroupCount(); ok {
		_spec.SetField(scan.FieldDuplicateGroupCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuplicateGroupCount(); ok {
		_spec.AddField(scan.FieldDuplicateGroupCount, field.TypeInt, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scan.TenantTable,
			Columns: []string{scan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scan.TenantTable,
			Columns: []string{scan.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InitiatedMachineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scan.InitiatedMachineTable,
			Columns: []string{scan.InitiatedMachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InitiatedMachineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scan.InitiatedMachineTable,
			Columns: []string{scan.InitiatedMachineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(machine.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DuplicateGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scan.DuplicateGroupsTable,
			Columns: []string{scan.DuplicateGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDuplicateGroupsIDs(); len(nodes) > 0 && !_u.mutation.DuplicateGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scan.DuplicateGroupsTable,
			Columns: []string{scan.DuplicateGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DuplicateGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scan.DuplicateGroupsTable,
			Columns: []string{scan.DuplicateGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(duplicategroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Scan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
