// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/tenant"
)

// Tenant is the model entity for the Tenant schema.
type Tenant struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PrimaryContact holds the value of the "primary_contact" field.
	PrimaryContact string `json:"primary_contact,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenantQuery when eager-loading is set.
	Edges        TenantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenantEdges holds the relations/edges for other nodes in the graph.
type TenantEdges struct {
	// Machines holds the value of the machines edge.
	Machines []*Machine `json:"machines,omitempty"`
	// Scans holds the value of the scans edge.
	Scans []*Scan `json:"scans,omitempty"`
	// DuplicateGroups holds the value of the duplicate_groups edge.
	DuplicateGroups []*DuplicateGroup `json:"duplicate_groups,omitempty"`
	// ActionAudits holds the value of the action_audits edge.
	ActionAudits []*ActionAudit `json:"action_audits,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// MachinesOrErr returns the Machines value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) MachinesOrErr() ([]*Machine, error) {
	if e.loadedTypes[0] {
		return e.Machines, nil
	}
	return nil, &NotLoadedError{edge: "machines"}
}

// ScansOrErr returns the Scans value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) ScansOrErr() ([]*Scan, error) {
	if e.loadedTypes[1] {
		return e.Scans, nil
	}
	return nil, &NotLoadedError{edge: "scans"}
}

// DuplicateGroupsOrErr returns the DuplicateGroups value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) DuplicateGroupsOrErr() ([]*DuplicateGroup, error) {
	if e.loadedTypes[2] {
		return e.DuplicateGroups, nil
	}
	return nil, &NotLoadedError{edge: "duplicate_groups"}
}

// ActionAuditsOrErr returns the ActionAudits value or an error if the edge
// was not loaded in eager-loading.
func (e TenantEdges) ActionAuditsOrErr() ([]*ActionAudit, error) {
	if e.loadedTypes[3] {
		return e.ActionAudits, nil
	}
	return nil, &NotLoadedError{edge: "action_audits"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tenant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenant.FieldSlug, tenant.FieldName, tenant.FieldDescription, tenant.FieldPrimaryContact:
			values[i] = new(sql.NullString)
		case tenant.FieldCreateTime, tenant.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case tenant.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tenant fields.
func (_m *Tenant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenant.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tenant.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case tenant.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case tenant.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case tenant.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tenant.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case tenant.FieldPrimaryContact:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field primary_contact", values[i])
			} else if value.Valid {
				_m.PrimaryContact = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tenant.
// This includes values selected through modifiers, order, etc.
func (_m *Tenant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMachines queries the "machines" edge of the Tenant entity.
func (_m *Tenant) QueryMachines() *MachineQuery {
	return NewTenantClient(_m.config).QueryMachines(_m)
}

// QueryScans queries the "scans" edge of the Tenant entity.
func (_m *Tenant) QueryScans() *ScanQuery {
	return NewTenantClient(_m.config).QueryScans(_m)
}

// QueryDuplicateGroups queries the "duplicate_groups" edge of the Tenant entity.
func (_m *Tenant) QueryDuplicateGroups() *DuplicateGroupQuery {
	return NewTenantClient(_m.config).QueryDuplicateGroups(_m)
}

// QueryActionAudits queries the "action_audits" edge of the Tenant entity.
func (_m *Tenant) QueryActionAudits() *ActionAuditQuery {
	return NewTenantClient(_m.config).QueryActionAudits(_m)
}

// Update returns a builder for updating this Tenant.
// Note that you need to call Tenant.Unwrap() before calling this method if this Tenant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tenant) Update() *TenantUpdateOne {
	return NewTenantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tenant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tenant) Unwrap() *Tenant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tenant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tenant) String() string {
	var builder strings.Builder
	builder.WriteString("Tenant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("primary_contact=")
	builder.WriteString(_m.PrimaryContact)
	builder.WriteByte(')')
	return builder.String()
}

// Tenants is a parsable slice of Tenant.
type Tenants []*Tenant
