// Code generated by ent, DO NOT EDIT.

package scan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the scan type in the database.
	Label = "scan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldInitiatedMachineID holds the string denoting the initiated_machine_id field in the database.
	FieldInitiatedMachineID = "initiated_machine_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldDuplicateGroupCount holds the string denoting the duplicate_group_count field in the database.
	FieldDuplicateGroupCount = "duplicate_group_count"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeInitiatedMachine holds the string denoting the initiated_machine edge name in mutations.
	EdgeInitiatedMachine = "initiated_machine"
	// EdgeDuplicateGroups holds the string denoting the duplicate_groups edge name in mutations.
	EdgeDuplicateGroups = "duplicate_groups"
	// Table holds the table name of the scan in the database.
	Table = "scans"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "scans"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// InitiatedMachineTable is the table that holds the initiated_machine relation/edge.
	InitiatedMachineTable = "scans"
	// InitiatedMachineInverseTable is the table name for the Machine entity.
	// It exists in this package in order to avoid circular dependency with the "machine" package.
	InitiatedMachineInverseTable = "machines"
	// InitiatedMachineColumn is the table column denoting the initiated_machine relation/edge.
	InitiatedMachineColumn = "initiated_machine_id"
	// DuplicateGroupsTable is the table that holds the duplicate_groups relation/edge.
	DuplicateGroupsTable = "duplicate_groups"
	// DuplicateGroupsInverseTable is the table name for the DuplicateGroup entity.
	// It exists in this package in order to avoid circular dependency with the "duplicategroup" package.
	DuplicateGroupsInverseTable = "duplicate_groups"
	// DuplicateGroupsColumn is the table column denoting the duplicate_groups relation/edge.
	DuplicateGroupsColumn = "scan_id"
)

// Columns holds all SQL columns for scan fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTenantID,
	FieldInitiatedMachineID,
	FieldName,
	FieldDescription,
	FieldStartedAt,
	FieldCompletedAt,
	FieldDuplicateGroupCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DuplicateGroupCountValidator is a validator for the "duplicate_group_count" field. It is called by the builders before save.
	DuplicateGroupCountValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Scan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByInitiatedMachineID orders the results by the initiated_machine_id field.
func ByInitiatedMachineID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatedMachineID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByDuplicateGroupCount orders the results by the duplicate_group_count field.
func ByDuplicateGroupCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuplicateGroupCount, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByInitiatedMachineField orders the results by initiated_machine field.
func ByInitiatedMachineField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInitiatedMachineStep(), sql.OrderByField(field, opts...))
	}
}

// ByDuplicateGroupsCount orders the results by duplicate_groups count.
func ByDuplicateGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDuplicateGroupsStep(), opts...)
	}
}

// ByDuplicateGroups orders the results by duplicate_groups terms.
func ByDuplicateGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDuplicateGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newInitiatedMachineStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InitiatedMachineInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InitiatedMachineTable, InitiatedMachineColumn),
	)
}
func newDuplicateGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DuplicateGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DuplicateGroupsTable, DuplicateGroupsColumn),
	)
}
