// Code generated by ent, DO NOT EDIT.

package scan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldUpdateTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldTenantID, v))
}

// InitiatedMachineID applies equality check predicate on the "initiated_machine_id" field. It's identical to InitiatedMachineIDEQ.
func InitiatedMachineID(v uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldInitiatedMachineID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldDescription, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldCompletedAt, v))
}

// DuplicateGroupCount applies equality check predicate on the "duplicate_group_count" field. It's identical to DuplicateGroupCountEQ.
func DuplicateGroupCount(v int) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldDuplicateGroupCount, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldLTE(FieldUpdateTime, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldTenantID, vs...))
}

// InitiatedMachineIDEQ applies the EQ predicate on the "initiated_machine_id" field.
func InitiatedMachineIDEQ(v uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldInitiatedMachineID, v))
}

// InitiatedMachineIDNEQ applies the NEQ predicate on the "initiated_machine_id" field.
func InitiatedMachineIDNEQ(v uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldInitiatedMachineID, v))
}

// InitiatedMachineIDIn applies the In predicate on the "initiated_machine_id" field.
func InitiatedMachineIDIn(vs ...uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldInitiatedMachineID, vs...))
}

// InitiatedMachineIDNotIn applies the NotIn predicate on the "initiated_machine_id" field.
func InitiatedMachineIDNotIn(vs ...uuid.UUID) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldInitiatedMachineID, vs...))
}

// InitiatedMachineIDIsNil applies the IsNil predicate on the "initiated_machine_id" field.
func InitiatedMachineIDIsNil() predicate.Scan {
	return predicate.Scan(sql.FieldIsNull(FieldInitiatedMachineID))
}

// InitiatedMachineIDNotNil applies the NotNil predicate on the "initiated_machine_id" field.
func InitiatedMachineIDNotNil() predicate.Scan {
	return predicate.Scan(sql.FieldNotNull(FieldInitiatedMachineID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Scan {
	return predicate.Scan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Scan {
	return predicate.Scan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Scan {
	return predicate.Scan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Scan {
	return predicate.Scan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Scan {
	return predicate.Scan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Scan {
	return predicate.Scan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Scan {
	return predicate.Scan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Scan {
	return predicate.Scan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Scan {
	return predicate.Scan(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Scan {
	return predicate.Scan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Scan {
	return predicate.Scan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Scan {
	return predicate.Scan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Scan {
	return predicate.Scan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Scan {
	return predicate.Scan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Scan {
	return predicate.Scan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Scan {
	return predicate.Scan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Scan {
	return predicate.Scan(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Scan {
	return predicate.Scan(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Scan {
	return predicate.Scan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Scan {
	return predicate.Scan(sql.FieldContainsFold(FieldDescription, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldLTE(FieldStartedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.Scan {
	return predicate.Scan(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.Scan {
	return predicate.Scan(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.Scan {
	return predicate.Scan(sql.FieldNotNull(FieldCompletedAt))
}

// DuplicateGroupCountEQ applies the EQ predicate on the "duplicate_group_count" field.
func DuplicateGroupCountEQ(v int) predicate.Scan {
	return predicate.Scan(sql.FieldEQ(FieldDuplicateGroupCount, v))
}

// DuplicateGroupCountNEQ applies the NEQ predicate on the "duplicate_group_count" field.
func DuplicateGroupCountNEQ(v int) predicate.Scan {
	return predicate.Scan(sql.FieldNEQ(FieldDuplicateGroupCount, v))
}

// DuplicateGroupCountIn applies the In predicate on the "duplicate_group_count" field.
func DuplicateGroupCountIn(vs ...int) predicate.Scan {
	return predicate.Scan(sql.FieldIn(FieldDuplicateGroupCount, vs...))
}

// DuplicateGroupCountNotIn applies the NotIn predicate on the "duplicate_group_count" field.
func DuplicateGroupCountNotIn(vs ...int) predicate.Scan {
	return predicate.Scan(sql.FieldNotIn(FieldDuplicateGroupCount, vs...))
}

// DuplicateGroupCountGT applies the GT predicate on the "duplicate_group_count" field.
func DuplicateGroupCountGT(v int) predicate.Scan {
	return predicate.Scan(sql.FieldGT(FieldDuplicateGroupCount, v))
}

// DuplicateGroupCountGTE applies the GTE predicate on the "duplicate_group_count" field.
func DuplicateGroupCountGTE(v int) predicate.Scan {
	return predicate.Scan(sql.FieldGTE(FieldDuplicateGroupCount, v))
}

// DuplicateGroupCountLT applies the LT predicate on the "duplicate_group_count" field.
func DuplicateGroupCountLT(v int) predicate.Scan {
	return predicate.Scan(sql.FieldLT(FieldDuplicateGroupCount, v))
}

// DuplicateGroupCountLTE applies the LTE predicate on the "duplicate_group_count" field.
func DuplicateGroupCountLTE(v int) predicate.Scan {
	return predicate.Scan(sql.FieldLTE(FieldDuplicateGroupCount, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Scan {
	return predicate.Scan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Scan {
	return predicate.Scan(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInitiatedMachine applies the HasEdge predicate on the "initiated_machine" edge.
func HasInitiatedMachine() predicate.Scan {
	return predicate.Scan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InitiatedMachineTable, InitiatedMachineColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInitiatedMachineWith applies the HasEdge predicate on the "initiated_machine" edge with a given conditions (other predicates).
func HasInitiatedMachineWith(preds ...predicate.Machine) predicate.Scan {
	return predicate.Scan(func(s *sql.Selector) {
		step := newInitiatedMachineStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDuplicateGroups applies the HasEdge predicate on the "duplicate_groups" edge.
func HasDuplicateGroups() predicate.Scan {
	return predicate.Scan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DuplicateGroupsTable, DuplicateGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDuplicateGroupsWith applies the HasEdge predicate on the "duplicate_groups" edge with a given conditions (other predicates).
func HasDuplicateGroupsWith(preds ...predicate.DuplicateGroup) predicate.Scan {
	return predicate.Scan(func(s *sql.Selector) {
		step := newDuplicateGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Scan) predicate.Scan {
	return predicate.Scan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Scan) predicate.Scan {
	return predicate.Scan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Scan) predicate.Scan {
	return predicate.Scan(sql.NotPredicates(p))
}
