// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActionAuditsColumns holds the columns for the "action_audits" table.
	ActionAuditsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "actor", Type: field.TypeString, Default: "system"},
		{Name: "action_type", Type: field.TypeEnum, Enums: []string{"assign_keeper", "delete_copies", "create_hardlinks", "quarantine", "retry", "note"}},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "performed_at", Type: field.TypeTime},
		{Name: "stubbed", Type: field.TypeBool, Default: false},
		{Name: "duplicate_group_id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
	}
	// ActionAuditsTable holds the schema information for the "action_audits" table.
	ActionAuditsTable = &schema.Table{
		Name:       "action_audits",
		Columns:    ActionAuditsColumns,
		PrimaryKey: []*schema.Column{ActionAuditsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "action_audits_duplicate_groups_action_audits",
				Columns:    []*schema.Column{ActionAuditsColumns[8]},
				RefColumns: []*schema.Column{DuplicateGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "action_audits_tenants_action_audits",
				Columns:    []*schema.Column{ActionAuditsColumns[9]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DuplicateGroupsColumns holds the columns for the "duplicate_groups" table.
	DuplicateGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "hash", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"review", "action_needed", "resolved", "archived"}, Default: "review"},
		{Name: "file_count", Type: field.TypeInt},
		{Name: "total_size_bytes", Type: field.TypeInt64},
		{Name: "keeper_machine_id", Type: field.TypeUUID, Nullable: true},
		{Name: "scan_id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
	}
	// DuplicateGroupsTable holds the schema information for the "duplicate_groups" table.
	DuplicateGroupsTable = &schema.Table{
		Name:       "duplicate_groups",
		Columns:    DuplicateGroupsColumns,
		PrimaryKey: []*schema.Column{DuplicateGroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "duplicate_groups_machines_keeper_groups",
				Columns:    []*schema.Column{DuplicateGroupsColumns[7]},
				RefColumns: []*schema.Column{MachinesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "duplicate_groups_scans_duplicate_groups",
				Columns:    []*schema.Column{DuplicateGroupsColumns[8]},
				RefColumns: []*schema.Column{ScansColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "duplicate_groups_tenants_duplicate_groups",
				Columns:    []*schema.Column{DuplicateGroupsColumns[9]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// FileInstancesColumns holds the columns for the "file_instances" table.
	FileInstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "path", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "checksum", Type: field.TypeString},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "quarantined", Type: field.TypeBool, Default: false},
		{Name: "duplicate_group_id", Type: field.TypeUUID},
		{Name: "machine_id", Type: field.TypeUUID},
	}
	// FileInstancesTable holds the schema information for the "file_instances" table.
	FileInstancesTable = &schema.Table{
		Name:       "file_instances",
		Columns:    FileInstancesColumns,
		PrimaryKey: []*schema.Column{FileInstancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "file_instances_duplicate_groups_file_instances",
				Columns:    []*schema.Column{FileInstancesColumns[8]},
				RefColumns: []*schema.Column{DuplicateGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "file_instances_machines_file_instances",
				Columns:    []*schema.Column{FileInstancesColumns[9]},
				RefColumns: []*schema.Column{MachinesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// MachinesColumns holds the columns for the "machines" table.
	MachinesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"personal_laptop", "server"}},
		{Name: "hostname", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeString, Nullable: true},
		{Name: "last_scan_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeUUID},
	}
	// MachinesTable holds the schema information for the "machines" table.
	MachinesTable = &schema.Table{
		Name:       "machines",
		Columns:    MachinesColumns,
		PrimaryKey: []*schema.Column{MachinesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "machines_tenants_machines",
				Columns:    []*schema.Column{MachinesColumns[8]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ScansColumns holds the columns for the "scans" table.
	ScansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "duplicate_group_count", Type: field.TypeInt},
		{Name: "initiated_machine_id", Type: field.TypeUUID, Nullable: true},
		{Name: "tenant_id", Type: field.TypeUUID},
	}
	// ScansTable holds the schema information for the "scans" table.
	ScansTable = &schema.Table{
		Name:       "scans",
		Columns:    ScansColumns,
		PrimaryKey: []*schema.Column{ScansColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "scans_machines_initiated_scans",
				Columns:    []*schema.Column{ScansColumns[8]},
				RefColumns: []*schema.Column{MachinesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "scans_tenants_scans",
				Columns:    []*schema.Column{ScansColumns[9]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "primary_contact", Type: field.TypeString, Nullable: true},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActionAuditsTable,
		DuplicateGroupsTable,
		FileInstancesTable,
		MachinesTable,
		ScansTable,
		TenantsTable,
	}
)

func init() {
	ActionAuditsTable.ForeignKeys[0].RefTable = DuplicateGroupsTable
	ActionAuditsTable.ForeignKeys[1].RefTable = TenantsTable
	DuplicateGroupsTable.ForeignKeys[0].RefTable = MachinesTable
	DuplicateGroupsTable.ForeignKeys[1].RefTable = ScansTable
	DuplicateGroupsTable.ForeignKeys[2].RefTable = TenantsTable
	FileInstancesTable.ForeignKeys[0].RefTable = DuplicateGroupsTable
	FileInstancesTable.ForeignKeys[1].RefTable = MachinesTable
	MachinesTable.ForeignKeys[0].RefTable = TenantsTable
	ScansTable.ForeignKeys[0].RefTable = MachinesTable
	ScansTable.ForeignKeys[1].RefTable = TenantsTable
}
