// Code generated by ent, DO NOT EDIT.

package fileinstance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldUpdateTime, v))
}

// DuplicateGroupID applies equality check predicate on the "duplicate_group_id" field. It's identical to DuplicateGroupIDEQ.
func DuplicateGroupID(v uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldDuplicateGroupID, v))
}

// MachineID applies equality check predicate on the "machine_id" field. It's identical to MachineIDEQ.
func MachineID(v uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldMachineID, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldPath, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldSizeBytes, v))
}

// Checksum applies equality check predicate on the "checksum" field. It's identical to ChecksumEQ.
func Checksum(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldChecksum, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldLastSeenAt, v))
}

// Quarantined applies equality check predicate on the "quarantined" field. It's identical to QuarantinedEQ.
func Quarantined(v bool) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldQuarantined, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLTE(FieldUpdateTime, v))
}

// DuplicateGroupIDEQ applies the EQ predicate on the "duplicate_group_id" field.
func DuplicateGroupIDEQ(v uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldDuplicateGroupID, v))
}

// DuplicateGroupIDNEQ applies the NEQ predicate on the "duplicate_group_id" field.
func DuplicateGroupIDNEQ(v uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldDuplicateGroupID, v))
}

// DuplicateGroupIDIn applies the In predicate on the "duplicate_group_id" field.
func DuplicateGroupIDIn(vs ...uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldDuplicateGroupID, vs...))
}

// DuplicateGroupIDNotIn applies the NotIn predicate on the "duplicate_group_id" field.
func DuplicateGroupIDNotIn(vs ...uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldDuplicateGroupID, vs...))
}

// MachineIDEQ applies the EQ predicate on the "machine_id" field.
func MachineIDEQ(v uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldMachineID, v))
}

// MachineIDNEQ applies the NEQ predicate on the "machine_id" field.
func MachineIDNEQ(v uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldMachineID, v))
}

// MachineIDIn applies the In predicate on the "machine_id" field.
func MachineIDIn(vs ...uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldMachineID, vs...))
}

// MachineIDNotIn applies the NotIn predicate on the "machine_id" field.
func MachineIDNotIn(vs ...uuid.UUID) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldMachineID, vs...))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldContainsFold(FieldPath, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLTE(FieldSizeBytes, v))
}

// ChecksumEQ applies the EQ predicate on the "checksum" field.
func ChecksumEQ(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldChecksum, v))
}

// ChecksumNEQ applies the NEQ predicate on the "checksum" field.
func ChecksumNEQ(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldChecksum, v))
}

// ChecksumIn applies the In predicate on the "checksum" field.
func ChecksumIn(vs ...string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldChecksum, vs...))
}

// ChecksumNotIn applies the NotIn predicate on the "checksum" field.
func ChecksumNotIn(vs ...string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldChecksum, vs...))
}

// ChecksumGT applies the GT predicate on the "checksum" field.
func ChecksumGT(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGT(FieldChecksum, v))
}

// ChecksumGTE applies the GTE predicate on the "checksum" field.
func ChecksumGTE(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGTE(FieldChecksum, v))
}

// ChecksumLT applies the LT predicate on the "checksum" field.
func ChecksumLT(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLT(FieldChecksum, v))
}

// ChecksumLTE applies the LTE predicate on the "checksum" field.
func ChecksumLTE(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLTE(FieldChecksum, v))
}

// ChecksumContains applies the Contains predicate on the "checksum" field.
func ChecksumContains(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldContains(FieldChecksum, v))
}

// ChecksumHasPrefix applies the HasPrefix predicate on the "checksum" field.
func ChecksumHasPrefix(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldHasPrefix(FieldChecksum, v))
}

// ChecksumHasSuffix applies the HasSuffix predicate on the "checksum" field.
func ChecksumHasSuffix(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldHasSuffix(FieldChecksum, v))
}

// ChecksumEqualFold applies the EqualFold predicate on the "checksum" field.
func ChecksumEqualFold(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEqualFold(FieldChecksum, v))
}

// ChecksumContainsFold applies the ContainsFold predicate on the "checksum" field.
func ChecksumContainsFold(v string) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldContainsFold(FieldChecksum, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldLTE(FieldLastSeenAt, v))
}

// QuarantinedEQ applies the EQ predicate on the "quarantined" field.
func QuarantinedEQ(v bool) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldEQ(FieldQuarantined, v))
}

// QuarantinedNEQ applies the NEQ predicate on the "quarantined" field.
func QuarantinedNEQ(v bool) predicate.FileInstance {
	return predicate.FileInstance(sql.FieldNEQ(FieldQuarantined, v))
}

// HasDuplicateGroup applies the HasEdge predicate on the "duplicate_group" edge.
func HasDuplicateGroup() predicate.FileInstance {
	return predicate.FileInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DuplicateGroupTable, DuplicateGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDuplicateGroupWith applies the HasEdge predicate on the "duplicate_group" edge with a given conditions (other predicates).
func HasDuplicateGroupWith(preds ...predicate.DuplicateGroup) predicate.FileInstance {
	return predicate.FileInstance(func(s *sql.Selector) {
		step := newDuplicateGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMachine applies the HasEdge predicate on the "machine" edge.
func HasMachine() predicate.FileInstance {
	return predicate.FileInstance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MachineTable, MachineColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMachineWith applies the HasEdge predicate on the "machine" edge with a given conditions (other predicates).
func HasMachineWith(preds ...predicate.Machine) predicate.FileInstance {
	return predicate.FileInstance(func(s *sql.Selector) {
		step := newMachineStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FileInstance) predicate.FileInstance {
	return predicate.FileInstance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FileInstance) predicate.FileInstance {
	return predicate.FileInstance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FileInstance) predicate.FileInstance {
	return predicate.FileInstance(sql.NotPredicates(p))
}
