openapi: 3.0.3
info:
  title: DupLynx Demo Server
  version: 0.1.0
  description: HTTP surface served by `duplynx serve` for evaluator workflows.
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Render launch dashboard
      description: Returns the templ-rendered landing page summarizing tenants, machines, and scans.
      responses:
        '200':
          description: HTML dashboard rendered successfully.
        '500':
          description: Server error while rendering dashboard.
  /tenants:
    get:
      summary: List available tenants
      description: Returns JSON for tenant picker (used by templ component hydration).
      responses:
        '200':
          description: Tenants returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TenantSummary'
        '500':
          description: Failure loading tenants.
  /tenants/{tenantSlug}/machines:
    get:
      summary: List machines for tenant
      parameters:
        - name: tenantSlug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Machines returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MachineSummary'
        '404':
          description: Tenant not found.
  /tenants/{tenantSlug}/scans:
    get:
      summary: List scans for tenant
      parameters:
        - name: tenantSlug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Scans returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScanSummary'
        '404':
          description: Tenant not found.
  /tenants/{tenantSlug}/scans/{scanId}/duplicate-groups:
    get:
      summary: List duplicate groups for scan
      parameters:
        - name: tenantSlug
          in: path
          required: true
          schema:
            type: string
        - name: scanId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Duplicate groups returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DuplicateGroup'
        '404':
          description: Scan or tenant not found.
  /assets/{assetPath}:
    get:
      summary: Serve static Tailwind asset
      parameters:
        - name: assetPath
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Static asset delivered.
        '404':
          description: Asset missing from disk bundle.
components:
  schemas:
    TenantSummary:
      type: object
      required: [slug, name]
      properties:
        slug:
          type: string
        name:
          type: string
        demo:
          type: boolean
    MachineSummary:
      type: object
      required: [id, displayName, lastScanAt]
      properties:
        id:
          type: string
          format: uuid
        hostname:
          type: string
        displayName:
          type: string
        lastScanAt:
          type: string
          format: date-time
    ScanSummary:
      type: object
      required: [id, machineId, status, completedAt, findingCount]
      properties:
        id:
          type: string
          format: uuid
        machineId:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, running, succeeded, failed]
        startedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
        findingCount:
          type: integer
    DuplicateGroup:
      type: object
      required: [id, title, severity]
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        severity:
          type: string
          enum: [low, medium, high]
        examplePath:
          type: string
        suggestedAction:
          type: string
