// Code generated by ent, DO NOT EDIT.

package machine

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the machine type in the database.
	Label = "machine"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldLastScanAt holds the string denoting the last_scan_at field in the database.
	FieldLastScanAt = "last_scan_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeKeeperGroups holds the string denoting the keeper_groups edge name in mutations.
	EdgeKeeperGroups = "keeper_groups"
	// EdgeFileInstances holds the string denoting the file_instances edge name in mutations.
	EdgeFileInstances = "file_instances"
	// EdgeInitiatedScans holds the string denoting the initiated_scans edge name in mutations.
	EdgeInitiatedScans = "initiated_scans"
	// Table holds the table name of the machine in the database.
	Table = "machines"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "machines"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// KeeperGroupsTable is the table that holds the keeper_groups relation/edge.
	KeeperGroupsTable = "duplicate_groups"
	// KeeperGroupsInverseTable is the table name for the DuplicateGroup entity.
	// It exists in this package in order to avoid circular dependency with the "duplicategroup" package.
	KeeperGroupsInverseTable = "duplicate_groups"
	// KeeperGroupsColumn is the table column denoting the keeper_groups relation/edge.
	KeeperGroupsColumn = "keeper_machine_id"
	// FileInstancesTable is the table that holds the file_instances relation/edge.
	FileInstancesTable = "file_instances"
	// FileInstancesInverseTable is the table name for the FileInstance entity.
	// It exists in this package in order to avoid circular dependency with the "fileinstance" package.
	FileInstancesInverseTable = "file_instances"
	// FileInstancesColumn is the table column denoting the file_instances relation/edge.
	FileInstancesColumn = "machine_id"
	// InitiatedScansTable is the table that holds the initiated_scans relation/edge.
	InitiatedScansTable = "scans"
	// InitiatedScansInverseTable is the table name for the Scan entity.
	// It exists in this package in order to avoid circular dependency with the "scan" package.
	InitiatedScansInverseTable = "scans"
	// InitiatedScansColumn is the table column denoting the initiated_scans relation/edge.
	InitiatedScansColumn = "initiated_machine_id"
)

// Columns holds all SQL columns for machine fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTenantID,
	FieldName,
	FieldCategory,
	FieldHostname,
	FieldRole,
	FieldLastScanAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Category defines the type for the "category" enum field.
type Category string

// Category values.
const (
	CategoryPersonalLaptop Category = "personal_laptop"
	CategoryServer         Category = "server"
)

func (c Category) String() string {
	return string(c)
}

// CategoryValidator is a validator for the "category" field enum values. It is called by the builders before save.
func CategoryValidator(c Category) error {
	switch c {
	case CategoryPersonalLaptop, CategoryServer:
		return nil
	default:
		return fmt.Errorf("machine: invalid enum value for category field: %q", c)
	}
}

// OrderOption defines the ordering options for the Machine queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByLastScanAt orders the results by the last_scan_at field.
func ByLastScanAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastScanAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByKeeperGroupsCount orders the results by keeper_groups count.
func ByKeeperGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newKeeperGroupsStep(), opts...)
	}
}

// ByKeeperGroups orders the results by keeper_groups terms.
func ByKeeperGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeeperGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFileInstancesCount orders the results by file_instances count.
func ByFileInstancesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFileInstancesStep(), opts...)
	}
}

// ByFileInstances orders the results by file_instances terms.
func ByFileInstances(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFileInstancesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInitiatedScansCount orders the results by initiated_scans count.
func ByInitiatedScansCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInitiatedScansStep(), opts...)
	}
}

// ByInitiatedScans orders the results by initiated_scans terms.
func ByInitiatedScans(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInitiatedScansStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newKeeperGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeeperGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, KeeperGroupsTable, KeeperGroupsColumn),
	)
}
func newFileInstancesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FileInstancesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FileInstancesTable, FileInstancesColumn),
	)
}
func newInitiatedScansStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InitiatedScansInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InitiatedScansTable, InitiatedScansColumn),
	)
}
