// Code generated by ent, DO NOT EDIT.

package machine

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldUpdateTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldName, v))
}

// Hostname applies equality check predicate on the "hostname" field. It's identical to HostnameEQ.
func Hostname(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldHostname, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldRole, v))
}

// LastScanAt applies equality check predicate on the "last_scan_at" field. It's identical to LastScanAtEQ.
func LastScanAt(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldLastScanAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldLTE(FieldUpdateTime, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldTenantID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Machine {
	return predicate.Machine(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Machine {
	return predicate.Machine(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Machine {
	return predicate.Machine(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Machine {
	return predicate.Machine(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Machine {
	return predicate.Machine(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Machine {
	return predicate.Machine(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Machine {
	return predicate.Machine(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Machine {
	return predicate.Machine(sql.FieldContainsFold(FieldName, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v Category) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v Category) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...Category) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...Category) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldCategory, vs...))
}

// HostnameEQ applies the EQ predicate on the "hostname" field.
func HostnameEQ(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldHostname, v))
}

// HostnameNEQ applies the NEQ predicate on the "hostname" field.
func HostnameNEQ(v string) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldHostname, v))
}

// HostnameIn applies the In predicate on the "hostname" field.
func HostnameIn(vs ...string) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldHostname, vs...))
}

// HostnameNotIn applies the NotIn predicate on the "hostname" field.
func HostnameNotIn(vs ...string) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldHostname, vs...))
}

// HostnameGT applies the GT predicate on the "hostname" field.
func HostnameGT(v string) predicate.Machine {
	return predicate.Machine(sql.FieldGT(FieldHostname, v))
}

// HostnameGTE applies the GTE predicate on the "hostname" field.
func HostnameGTE(v string) predicate.Machine {
	return predicate.Machine(sql.FieldGTE(FieldHostname, v))
}

// HostnameLT applies the LT predicate on the "hostname" field.
func HostnameLT(v string) predicate.Machine {
	return predicate.Machine(sql.FieldLT(FieldHostname, v))
}

// HostnameLTE applies the LTE predicate on the "hostname" field.
func HostnameLTE(v string) predicate.Machine {
	return predicate.Machine(sql.FieldLTE(FieldHostname, v))
}

// HostnameContains applies the Contains predicate on the "hostname" field.
func HostnameContains(v string) predicate.Machine {
	return predicate.Machine(sql.FieldContains(FieldHostname, v))
}

// HostnameHasPrefix applies the HasPrefix predicate on the "hostname" field.
func HostnameHasPrefix(v string) predicate.Machine {
	return predicate.Machine(sql.FieldHasPrefix(FieldHostname, v))
}

// HostnameHasSuffix applies the HasSuffix predicate on the "hostname" field.
func HostnameHasSuffix(v string) predicate.Machine {
	return predicate.Machine(sql.FieldHasSuffix(FieldHostname, v))
}

// HostnameIsNil applies the IsNil predicate on the "hostname" field.
func HostnameIsNil() predicate.Machine {
	return predicate.Machine(sql.FieldIsNull(FieldHostname))
}

// HostnameNotNil applies the NotNil predicate on the "hostname" field.
func HostnameNotNil() predicate.Machine {
	return predicate.Machine(sql.FieldNotNull(FieldHostname))
}

// HostnameEqualFold applies the EqualFold predicate on the "hostname" field.
func HostnameEqualFold(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEqualFold(FieldHostname, v))
}

// HostnameContainsFold applies the ContainsFold predicate on the "hostname" field.
func HostnameContainsFold(v string) predicate.Machine {
	return predicate.Machine(sql.FieldContainsFold(FieldHostname, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.Machine {
	return predicate.Machine(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.Machine {
	return predicate.Machine(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.Machine {
	return predicate.Machine(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.Machine {
	return predicate.Machine(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.Machine {
	return predicate.Machine(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.Machine {
	return predicate.Machine(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.Machine {
	return predicate.Machine(sql.FieldHasSuffix(FieldRole, v))
}

// RoleIsNil applies the IsNil predicate on the "role" field.
func RoleIsNil() predicate.Machine {
	return predicate.Machine(sql.FieldIsNull(FieldRole))
}

// RoleNotNil applies the NotNil predicate on the "role" field.
func RoleNotNil() predicate.Machine {
	return predicate.Machine(sql.FieldNotNull(FieldRole))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.Machine {
	return predicate.Machine(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.Machine {
	return predicate.Machine(sql.FieldContainsFold(FieldRole, v))
}

// LastScanAtEQ applies the EQ predicate on the "last_scan_at" field.
func LastScanAtEQ(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldEQ(FieldLastScanAt, v))
}

// LastScanAtNEQ applies the NEQ predicate on the "last_scan_at" field.
func LastScanAtNEQ(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldNEQ(FieldLastScanAt, v))
}

// LastScanAtIn applies the In predicate on the "last_scan_at" field.
func LastScanAtIn(vs ...time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldIn(FieldLastScanAt, vs...))
}

// LastScanAtNotIn applies the NotIn predicate on the "last_scan_at" field.
func LastScanAtNotIn(vs ...time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldNotIn(FieldLastScanAt, vs...))
}

// LastScanAtGT applies the GT predicate on the "last_scan_at" field.
func LastScanAtGT(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldGT(FieldLastScanAt, v))
}

// LastScanAtGTE applies the GTE predicate on the "last_scan_at" field.
func LastScanAtGTE(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldGTE(FieldLastScanAt, v))
}

// LastScanAtLT applies the LT predicate on the "last_scan_at" field.
func LastScanAtLT(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldLT(FieldLastScanAt, v))
}

// LastScanAtLTE applies the LTE predicate on the "last_scan_at" field.
func LastScanAtLTE(v time.Time) predicate.Machine {
	return predicate.Machine(sql.FieldLTE(FieldLastScanAt, v))
}

// LastScanAtIsNil applies the IsNil predicate on the "last_scan_at" field.
func LastScanAtIsNil() predicate.Machine {
	return predicate.Machine(sql.FieldIsNull(FieldLastScanAt))
}

// LastScanAtNotNil applies the NotNil predicate on the "last_scan_at" field.
func LastScanAtNotNil() predicate.Machine {
	return predicate.Machine(sql.FieldNotNull(FieldLastScanAt))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Machine {
	return predicate.Machine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Machine {
	return predicate.Machine(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKeeperGroups applies the HasEdge predicate on the "keeper_groups" edge.
func HasKeeperGroups() predicate.Machine {
	return predicate.Machine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, KeeperGroupsTable, KeeperGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeeperGroupsWith applies the HasEdge predicate on the "keeper_groups" edge with a given conditions (other predicates).
func HasKeeperGroupsWith(preds ...predicate.DuplicateGroup) predicate.Machine {
	return predicate.Machine(func(s *sql.Selector) {
		step := newKeeperGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFileInstances applies the HasEdge predicate on the "file_instances" edge.
func HasFileInstances() predicate.Machine {
	return predicate.Machine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FileInstancesTable, FileInstancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFileInstancesWith applies the HasEdge predicate on the "file_instances" edge with a given conditions (other predicates).
func HasFileInstancesWith(preds ...predicate.FileInstance) predicate.Machine {
	return predicate.Machine(func(s *sql.Selector) {
		step := newFileInstancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInitiatedScans applies the HasEdge predicate on the "initiated_scans" edge.
func HasInitiatedScans() predicate.Machine {
	return predicate.Machine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InitiatedScansTable, InitiatedScansColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInitiatedScansWith applies the HasEdge predicate on the "initiated_scans" edge with a given conditions (other predicates).
func HasInitiatedScansWith(preds ...predicate.Scan) predicate.Machine {
	return predicate.Machine(func(s *sql.Selector) {
		step := newInitiatedScansStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Machine) predicate.Machine {
	return predicate.Machine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Machine) predicate.Machine {
	return predicate.Machine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Machine) predicate.Machine {
	return predicate.Machine(sql.NotPredicates(p))
}
