// Code generated by ent, DO NOT EDIT.

package duplicategroup

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the duplicategroup type in the database.
	Label = "duplicate_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldScanID holds the string denoting the scan_id field in the database.
	FieldScanID = "scan_id"
	// FieldKeeperMachineID holds the string denoting the keeper_machine_id field in the database.
	FieldKeeperMachineID = "keeper_machine_id"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFileCount holds the string denoting the file_count field in the database.
	FieldFileCount = "file_count"
	// FieldTotalSizeBytes holds the string denoting the total_size_bytes field in the database.
	FieldTotalSizeBytes = "total_size_bytes"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeScan holds the string denoting the scan edge name in mutations.
	EdgeScan = "scan"
	// EdgeKeeperMachine holds the string denoting the keeper_machine edge name in mutations.
	EdgeKeeperMachine = "keeper_machine"
	// EdgeFileInstances holds the string denoting the file_instances edge name in mutations.
	EdgeFileInstances = "file_instances"
	// EdgeActionAudits holds the string denoting the action_audits edge name in mutations.
	EdgeActionAudits = "action_audits"
	// Table holds the table name of the duplicategroup in the database.
	Table = "duplicate_groups"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "duplicate_groups"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// ScanTable is the table that holds the scan relation/edge.
	ScanTable = "duplicate_groups"
	// ScanInverseTable is the table name for the Scan entity.
	// It exists in this package in order to avoid circular dependency with the "scan" package.
	ScanInverseTable = "scans"
	// ScanColumn is the table column denoting the scan relation/edge.
	ScanColumn = "scan_id"
	// KeeperMachineTable is the table that holds the keeper_machine relation/edge.
	KeeperMachineTable = "duplicate_groups"
	// KeeperMachineInverseTable is the table name for the Machine entity.
	// It exists in this package in order to avoid circular dependency with the "machine" package.
	KeeperMachineInverseTable = "machines"
	// KeeperMachineColumn is the table column denoting the keeper_machine relation/edge.
	KeeperMachineColumn = "keeper_machine_id"
	// FileInstancesTable is the table that holds the file_instances relation/edge.
	FileInstancesTable = "file_instances"
	// FileInstancesInverseTable is the table name for the FileInstance entity.
	// It exists in this package in order to avoid circular dependency with the "fileinstance" package.
	FileInstancesInverseTable = "file_instances"
	// FileInstancesColumn is the table column denoting the file_instances relation/edge.
	FileInstancesColumn = "duplicate_group_id"
	// ActionAuditsTable is the table that holds the action_audits relation/edge.
	ActionAuditsTable = "action_audits"
	// ActionAuditsInverseTable is the table name for the ActionAudit entity.
	// It exists in this package in order to avoid circular dependency with the "actionaudit" package.
	ActionAuditsInverseTable = "action_audits"
	// ActionAuditsColumn is the table column denoting the action_audits relation/edge.
	ActionAuditsColumn = "duplicate_group_id"
)

// Columns holds all SQL columns for duplicategroup fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTenantID,
	FieldScanID,
	FieldKeeperMachineID,
	FieldHash,
	FieldStatus,
	FieldFileCount,
	FieldTotalSizeBytes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// FileCountValidator is a validator for the "file_count" field. It is called by the builders before save.
	FileCountValidator func(int) error
	// TotalSizeBytesValidator is a validator for the "total_size_bytes" field. It is called by the builders before save.
	TotalSizeBytesValidator func(int64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusReview is the default value of the Status enum.
const DefaultStatus = StatusReview

// Status values.
const (
	StatusReview       Status = "review"
	StatusActionNeeded Status = "action_needed"
	StatusResolved     Status = "resolved"
	StatusArchived     Status = "archived"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusReview, StatusActionNeeded, StatusResolved, StatusArchived:
		return nil
	default:
		return fmt.Errorf("duplicategroup: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the DuplicateGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByScanID orders the results by the scan_id field.
func ByScanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScanID, opts...).ToFunc()
}

// ByKeeperMachineID orders the results by the keeper_machine_id field.
func ByKeeperMachineID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeeperMachineID, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFileCount orders the results by the file_count field.
func ByFileCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileCount, opts...).ToFunc()
}

// ByTotalSizeBytes orders the results by the total_size_bytes field.
func ByTotalSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalSizeBytes, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByScanField orders the results by scan field.
func ByScanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScanStep(), sql.OrderByField(field, opts...))
	}
}

// ByKeeperMachineField orders the results by keeper_machine field.
func ByKeeperMachineField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeeperMachineStep(), sql.OrderByField(field, opts...))
	}
}

// ByFileInstancesCount orders the results by file_instances count.
func ByFileInstancesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFileInstancesStep(), opts...)
	}
}

// ByFileInstances orders the results by file_instances terms.
func ByFileInstances(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFileInstancesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByActionAuditsCount orders the results by action_audits count.
func ByActionAuditsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newActionAuditsStep(), opts...)
	}
}

// ByActionAudits orders the results by action_audits terms.
func ByActionAudits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActionAuditsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newScanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ScanTable, ScanColumn),
	)
}
func newKeeperMachineStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeeperMachineInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, KeeperMachineTable, KeeperMachineColumn),
	)
}
func newFileInstancesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FileInstancesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FileInstancesTable, FileInstancesColumn),
	)
}
func newActionAuditsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActionAuditsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ActionAuditsTable, ActionAuditsColumn),
	)
}
