// Code generated by ent, DO NOT EDIT.

package duplicategroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mcmx/duplynx/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldUpdateTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldTenantID, v))
}

// ScanID applies equality check predicate on the "scan_id" field. It's identical to ScanIDEQ.
func ScanID(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldScanID, v))
}

// KeeperMachineID applies equality check predicate on the "keeper_machine_id" field. It's identical to KeeperMachineIDEQ.
func KeeperMachineID(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldKeeperMachineID, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldHash, v))
}

// FileCount applies equality check predicate on the "file_count" field. It's identical to FileCountEQ.
func FileCount(v int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldFileCount, v))
}

// TotalSizeBytes applies equality check predicate on the "total_size_bytes" field. It's identical to TotalSizeBytesEQ.
func TotalSizeBytes(v int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldTotalSizeBytes, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLTE(FieldUpdateTime, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldTenantID, vs...))
}

// ScanIDEQ applies the EQ predicate on the "scan_id" field.
func ScanIDEQ(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldScanID, v))
}

// ScanIDNEQ applies the NEQ predicate on the "scan_id" field.
func ScanIDNEQ(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldScanID, v))
}

// ScanIDIn applies the In predicate on the "scan_id" field.
func ScanIDIn(vs ...uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldScanID, vs...))
}

// ScanIDNotIn applies the NotIn predicate on the "scan_id" field.
func ScanIDNotIn(vs ...uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldScanID, vs...))
}

// KeeperMachineIDEQ applies the EQ predicate on the "keeper_machine_id" field.
func KeeperMachineIDEQ(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldKeeperMachineID, v))
}

// KeeperMachineIDNEQ applies the NEQ predicate on the "keeper_machine_id" field.
func KeeperMachineIDNEQ(v uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldKeeperMachineID, v))
}

// KeeperMachineIDIn applies the In predicate on the "keeper_machine_id" field.
func KeeperMachineIDIn(vs ...uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldKeeperMachineID, vs...))
}

// KeeperMachineIDNotIn applies the NotIn predicate on the "keeper_machine_id" field.
func KeeperMachineIDNotIn(vs ...uuid.UUID) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldKeeperMachineID, vs...))
}

// KeeperMachineIDIsNil applies the IsNil predicate on the "keeper_machine_id" field.
func KeeperMachineIDIsNil() predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIsNull(FieldKeeperMachineID))
}

// KeeperMachineIDNotNil applies the NotNil predicate on the "keeper_machine_id" field.
func KeeperMachineIDNotNil() predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotNull(FieldKeeperMachineID))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldContainsFold(FieldHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldStatus, vs...))
}

// FileCountEQ applies the EQ predicate on the "file_count" field.
func FileCountEQ(v int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldFileCount, v))
}

// FileCountNEQ applies the NEQ predicate on the "file_count" field.
func FileCountNEQ(v int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldFileCount, v))
}

// FileCountIn applies the In predicate on the "file_count" field.
func FileCountIn(vs ...int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldFileCount, vs...))
}

// FileCountNotIn applies the NotIn predicate on the "file_count" field.
func FileCountNotIn(vs ...int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldFileCount, vs...))
}

// FileCountGT applies the GT predicate on the "file_count" field.
func FileCountGT(v int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGT(FieldFileCount, v))
}

// FileCountGTE applies the GTE predicate on the "file_count" field.
func FileCountGTE(v int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGTE(FieldFileCount, v))
}

// FileCountLT applies the LT predicate on the "file_count" field.
func FileCountLT(v int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLT(FieldFileCount, v))
}

// FileCountLTE applies the LTE predicate on the "file_count" field.
func FileCountLTE(v int) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLTE(FieldFileCount, v))
}

// TotalSizeBytesEQ applies the EQ predicate on the "total_size_bytes" field.
func TotalSizeBytesEQ(v int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldEQ(FieldTotalSizeBytes, v))
}

// TotalSizeBytesNEQ applies the NEQ predicate on the "total_size_bytes" field.
func TotalSizeBytesNEQ(v int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNEQ(FieldTotalSizeBytes, v))
}

// TotalSizeBytesIn applies the In predicate on the "total_size_bytes" field.
func TotalSizeBytesIn(vs ...int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldIn(FieldTotalSizeBytes, vs...))
}

// TotalSizeBytesNotIn applies the NotIn predicate on the "total_size_bytes" field.
func TotalSizeBytesNotIn(vs ...int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldNotIn(FieldTotalSizeBytes, vs...))
}

// TotalSizeBytesGT applies the GT predicate on the "total_size_bytes" field.
func TotalSizeBytesGT(v int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGT(FieldTotalSizeBytes, v))
}

// TotalSizeBytesGTE applies the GTE predicate on the "total_size_bytes" field.
func TotalSizeBytesGTE(v int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldGTE(FieldTotalSizeBytes, v))
}

// TotalSizeBytesLT applies the LT predicate on the "total_size_bytes" field.
func TotalSizeBytesLT(v int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLT(FieldTotalSizeBytes, v))
}

// TotalSizeBytesLTE applies the LTE predicate on the "total_size_bytes" field.
func TotalSizeBytesLTE(v int64) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.FieldLTE(FieldTotalSizeBytes, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasScan applies the HasEdge predicate on the "scan" edge.
func HasScan() predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScanTable, ScanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScanWith applies the HasEdge predicate on the "scan" edge with a given conditions (other predicates).
func HasScanWith(preds ...predicate.Scan) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := newScanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKeeperMachine applies the HasEdge predicate on the "keeper_machine" edge.
func HasKeeperMachine() predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KeeperMachineTable, KeeperMachineColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeeperMachineWith applies the HasEdge predicate on the "keeper_machine" edge with a given conditions (other predicates).
func HasKeeperMachineWith(preds ...predicate.Machine) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := newKeeperMachineStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFileInstances applies the HasEdge predicate on the "file_instances" edge.
func HasFileInstances() predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FileInstancesTable, FileInstancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFileInstancesWith applies the HasEdge predicate on the "file_instances" edge with a given conditions (other predicates).
func HasFileInstancesWith(preds ...predicate.FileInstance) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := newFileInstancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActionAudits applies the HasEdge predicate on the "action_audits" edge.
func HasActionAudits() predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ActionAuditsTable, ActionAuditsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionAuditsWith applies the HasEdge predicate on the "action_audits" edge with a given conditions (other predicates).
func HasActionAuditsWith(preds ...predicate.ActionAudit) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(func(s *sql.Selector) {
		step := newActionAuditsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DuplicateGroup) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DuplicateGroup) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DuplicateGroup) predicate.DuplicateGroup {
	return predicate.DuplicateGroup(sql.NotPredicates(p))
}
