name: DupLynx CI

on:
  push:
    branches: ["main", "001-create-duplynx"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Go mod tidy
        run: make tidy
      - name: Run lint
        run: make lint
      - name: Run unit/integration tests
        run: make test
      - name: Run e2e smoke
        run: make e2e
      - name: Run performance benchmarks
        run: make perf
