name: DupLynx CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Go mod tidy
        run: make tidy
      - name: Run full CI suite (8 minute budget)
        run: make ci
